content/docs/reference/autocert/autocert-directory.md, content/docs/reference/autocert/autocert-must-staple.md, content/docs/reference/autocert/readme.md, content/docs/reference/reference.json, content/docs/topics/certificates.mdx
With this change, the reference page behaves the way routes does, as an index for the section.
=> Adjust path for Autocert

content/docs/reference/reference.json, src/pages/markdown-page.md
Doesn't apply in Console, where certificate fields are drop downs.
Will resolve https://github.com/pomerium/pomerium-console/issues/2596 once merged and console pulls the changes.
=> remove shortdocs for ent certs

content/docs/install/index.mdx, content/docs/tcp/index.md, docusaurus.config.js
This makes category index page URLs consistent with other pages, and should also reduce our search index size by removing dupes.
=> remove trailing slash

docusaurus.config.js, src/theme/Footer/Links/MultiColumn/index.js
Sets the link for the Pomerium logo to the marketing site.
Resolves https://github.com/pomerium/internal/issues/879
=> Set logo link to marketing site

content/docs/install/from-source.mdx, content/examples/config/config.minimal.yaml.md
Minor updates to our "From Source" install doc.
- Reference `make build` to skip tests.
- remove redundant `make` when running
- Update example minimal config with optional keys for mkcert-based local install.
=> Update "From Source" installation

content/docs/reference/jwt-claim-headers.md, content/docs/reference/routes/set-request-headers.md
Might resolve https://github.com/pomerium/pomerium/issues/3424
Crosslinks reference pages for `set_request_headers` and `jwt_claim_headers`.
=> crosslink static and dynamic header ref pages

docusaurus.config.js
Excludes the `examples` directory from the sitemap. The contents of that directory are used as embedded example content, but not displayed directly.
=> exclude examples dir from sitemap

content/docs/tcp/client.mdx
Describes how to add Pomerium Desktop to autostart for Windows, MacOS, Gnome and KDE (linux).
This would resolve https://github.com/pomerium/internal/issues/873.
=> Document autostart for common desktops

content/docs/enterprise/install/quickstart.mdx
Missed a callout that was still in the Vuepress format.
=> Hotfix: Outdated partial callout

content/docs/identity-providers/cognito.mdx
Reviewed the Cognito idp doc. Still works fine, provided some more clear copy and hid the pool creation into an expandable section. 
Resolves https://github.com/pomerium/docs/issues/77
=> Cognito - Doc Review

content/docs/troubleshooting.mdx, docusaurus.config.js, src/components/docVersions.json
v17 was being referred to in several different ways including .io / .com domains. 
Updated references to use the `v17` subdomain to match the corresponding branch name.
=> docs: fix references to v17

src/components/docVersions.json
We need to migrate the pomerium.io domain to be an alias to pomerium.com in Netlify. Unfortunately, this means losing "vanity" urls for archived versions of pomerium docs.
=> chore: update docVersions.json to use netlify domain

content/docs/topics/getting-users-identity.md
Add an example of how to verify a user's identity in a single page javascript application.
Fixes https://github.com/pomerium/documentation/issues/101
=> identity: add single page app example

content/docs/reference/autocert/readme.md
Update the documentation for autocert to reflect what TLS-ALPN-01 will require.
=> autocert: update documentation

content/docs/reference/autocert/readme.md
=> add link to cert-manager, which is what k8s users need to use

content/docs/capabilities/tcp.mdx, static/_redirects
Fixes 404 redirect links, specifically for /docs/k8s and /enterprise/ links.
=> updates redirects to fix 404 links

content/docs/deploying/k8s/quickstart.mdx, content/docs/identity-providers/google.mdx, content/docs/index.mdx, content/docs/releases/core.mdx, content/docs/releases/pomerium-cli.mdx, content/docs/releases/pomerium-desktop.mdx
Updates several typos and syntax errors across Pomerium docs, including:
- K8s quickstart 
- Google IdP guide
- Sidebar > Releases
- What is Pomerium? 
Fixes #166
=> Docs: zpain8464/fix docs typos

static/_redirects
Redirects branding page from /docs/enterprise/branding to /docs/capabilities/branding
=> Docs: redirects branding page

content/docs/concepts/routes.mdx
The [routes page](https://www.pomerium.com/docs/concepts/routes) has two broken links:
- An attempted link to Reference: Routes goes nowhere.
- the link to Namepaces just goes back to the same page with a non-existent anchor
I'm not sure how these anchor-thingies work and have no way of testing it, but I think this PR fixed both.
=> Fix links on routes page

static/_redirects
**Problem:** Redirected links with a `.md` file extension still 404. 
For example: 
`/docs/k8s/ingress.md /docs/deploying/k8s/ingress` still 404s.
**Solution:** Removing the `.md` file extension from the link redirects the link as it should. 
For example:
`/docs/k8s/ingress /docs/deploying/k8s/ingress`
Links with an `html` file extension don't seem to 404.
=> Docs: trims .md file extensions from links redirects file

content/docs/quickstart.mdx
After the re-org merge, the Core Quick-Start page was modified to the extent that it was unusable for users. For example, the `ConfigDocker` sample file is missing and steps are duplicated and out of order:
This PR resolves these issues.
=> Docs: Fixes Quick-Start typos and missing config file after re-org

static/_redirects
Redirects links from issues submitted under [pomerium/internals](https://github.com/pomerium/internal/issues/1075)
Fixes:
- [1147](https://github.com/pomerium/internal/issues/1147)
- [1156](https://github.com/pomerium/internal/issues/1156)
- [1158](https://github.com/pomerium/internal/issues/1158)
- [1160](https://github.com/pomerium/internal/issues/1160)
- [1162](https://github.com/pomerium/internal/issues/1162)
- [1164](https://github.com/pomerium/internal/issues/1164)
- [1166](https://github.com/pomerium/internal/issues/1166)
- [1185](https://github.com/pomerium/internal/issues/1185)
- [1172](https://github.com/pomerium/internal/issues/1172)
- [1174](https://github.com/pomerium/internal/issues/1174)
- [1176](https://github.com/pomerium/internal/issues/1176)
- …
=> docs: redirects 10 links

static/_redirects
Redirects broken/404ing links on `pomerium.com/integrations`. 
Some integrations, like Fedora and CentOS, don't have a page to redirect to.
Others, like Argo and Cloud Run, should include links to the corresponding guide.
=> Docs: adds redirects for 404 links on /integrations/ page

static/_redirects
Fixes a slew of redirects from re-org, and fixes closed issues that continued to 404 after merging.
=> docs: more re-org redirects

static/_redirects
Fixes: 
- https://github.com/pomerium/internal/issues/1127
- https://github.com/pomerium/internal/issues/1178
- https://github.com/pomerium/internal/issues/1180
- https://github.com/pomerium/internal/issues/1182
- https://github.com/pomerium/internal/issues/1177
=> docs: redirects 404ing blog urls

docusaurus.config.js
Obviously, not to backport. 
Signed-off-by: Bobby DeSimone <bobbydesimone@gmail.com>
=> make clear current version is vNext on main

static/_redirects
The blog redirects and `original-request-context` links still 404. Hopefully, this will fix those links.
=> docs: fixes a few more issues from broken re-org links

content/docs/capabilities/tcp.mdx, content/docs/capabilities/tcp/client.mdx
Fixes https://github.com/pomerium/internal/issues/1203
You can now specify TCP routes with a separate path to indicate a specialized bastion host:
```
tcp+https://proxy.example.com:8443/ssh.example.com:22
```
This does the same thing the custom `pomerium-url` option did, but does so more explicitly so that it works properly with Pomerium TLS certificate selection.
=> tcp: update advanced docs for new URL format

.pre-commit-config.yaml
Fixes https://github.com/pomerium/documentation/issues/237
Add a pre-commit hook for running cspell
=> cspell: add pre-commit hook

content/docs/reference/signing-key.md
Update signing key docs to mention multiple key support and add a section about key rotation.
Fixes https://github.com/pomerium/documentation/issues/216
=> reference: update signing key docs

content/docs/capabilities/jwt-verification.mdx, sidebars.js
Adds a JS SDK capabilities page titled "JWT Verification". Includes:
- Links to NPM and GH repos
- Quick code sample in a React app
- Link to JS SDK guide
- Verifier class and methods reference 
- Links to backend SDKs (Go/JS SDK for Express/Node)
=> Docs: adds JS SDK capabilities page

content/docs/guides/nginx.mdx, content/docs/guides/traefik-ingress.mdx, content/docs/reference/forward-auth.md
Adds Forward Auth deprecation notices in Forward Auth reference, NGINX and Traefik guides.
=> Docs: adds deprecation notices to forward auth ref, nginx and traefik guides

content/docs/identity-providers/okta.mdx
The docs were completely reorganized, so it was difficult to the right substitute for the 404ing link.
=> Docs: adds Okta sign-in quickstarts link to Okta IdP guide

static/_redirects
SHOULD fix the following links:
=> Docs: fixes redirects 

content/docs/releases/enterprise/install/kustomize.mdx, k8s/config-template/ingress-console.yaml, k8s/console/deployment/args.yaml, k8s/console/deployment/image.yaml, k8s/core/kustomization.yaml
Blocked by https://github.com/pomerium/internal/issues/1291
=> [blocked] v0.21.x: bump core version in enterprise guide

cspell.json, static/_redirects
This is just a housekeeping PR to clean up the redirects file:
- Deletes duplicate links 
- Rearranges links (somewhat) into categories.
- Labels links that use 2 or more lines (multiple redirects per link)
- Labels links that still 404 or redirect incorrectly (small handful)
I also found opportunities to consolidate links with a `:splat` but I'd like to do those in separate PRs one at a time so I can  test these out and make issues for them.
=> Docs: cleans up redirects

content/docs/releases/enterprise/install/installation.mdx
Adds enterprise installations page with instructions on pulling the RPM and DEB OS packages and Docker image from Cloudsmith.
=> Docs: adds enterprise installations page

static/_redirects
This PR:
- Cleans up 404s from GSC.
- Adds a `/recipe/` splat to reduce links in the file
- 301s deprecated Forward Auth to v20 docs
Should fix the following:
=> Docs: fixes redirects

content/docs/releases/enterprise/configure.md
Updates the Authn Service URL in GUI Config:
- Deprecates including the URL in Console config
- Instructs users to use external route URL for device enrollment
=> Docs: updates authenticate service url reference in GUI Config

content/docs/releases/changelog.mdx
Adds Core changelogs for the following releases:
- v0.21.1
- v0.21.2
- v0.21.3
The upgrade guide link in the changelog will need to be updated once the guides are ready.
=> Docs: adds v21 changelogs

content/docs/releases/upgrading.mdx
This PR updates the v12 section of the upgrade guide to specify that impersonation is no longer supported for Core, but is supported for Enterprise customers by creating Service Accounts.
It adds links to the Management API and Service Account capabilities pages.
=> Docs: updates upgrade guide impersonation notice and adds links pages

content/docs/guides/cloud-run.mdx
Adds an oudated notice to the CloudRun guide: https://www.pomerium.com/docs/guides/cloud-run
I went ahead and linked to the last working version, but not sure if we should include that or not since it's v17.
=> Docs: adds notice to cloud run guide

content/docs/capabilities/hosted-authenticate-service.md, content/docs/capabilities/self-hosted-authenticate-service.md, content/docs/identity-providers/index.md, content/docs/reference/authenticate-callback-path.md, content/docs/reference/authenticate-internal-service-url.md, content/docs/reference/authenticate-service-url.md, content/docs/reference/identity-provider-client-id.md, content/docs/reference/identity-provider-client-secret-file.md, content/docs/reference/identity-provider-client-secret.md, content/docs/reference/identity-provider-name.md, content/docs/reference/identity-provider-refresh-directory-settings.md, content/docs/reference/identity-provider-request-params.md, content/docs/reference/identity-provider-scopes.md, content/docs/reference/identity-provider-url.md, sidebars.js
This PR adds a Hosted Authenticate Service capabilities page and sidebar slice. 
This is a first draft. It could probably be more informative in sections like Less time to deploy and Privacy considerations. 
Once a Hosted Authenticate URL reference page is live, it will also need to be linked here.
=> Docs: Hosted Authenticate Service capabilities page and sidebar

content/docs/capabilities/ppl.mdx, content/docs/deploying/k8s/reference.md, content/docs/releases/enterprise/install/installation.mdx
Just a cleanup PR to run prettier on the following pages:
- /docs/deploying/k8s/reference
- /docs/capabilities/ppl
- /docs/releases/enterprise/install/installation
=> Docs: runs prettier on ppl, k8s reference, and installation

content/docs/releases/changelog.mdx
Closes #613 
Updates the Core Changelog headers to H3s. 
Suggestion: What if we organized headers alphabetically? This would give a more uniform look to the Changelog.
=> updates core changelog headers for consistency

content/docs/deploying/from-source.mdx, cspell.json
On the Deploying / From Source page, add 'golangci-lint' to the Prerequisites list (linking to the local installation instructions). This is required by the `all` make target.
=> Docs: add golangci-lint as a build prerequisite

content/docs/reference/reference.json, static/_redirects
Removes deprecated `/policy/*` references from `/docs/reference/reference.json` and manually redirects links to v14 docs. 
The previous redirects 301 redirected to v14, but were still 404ing. I manually directed each deprecated link to `0-14-0.docs.pomerium/reference` to hopefully prevent 404ing.
=> Docs: reference json update

content/docs/capabilities/programmatic-access.mdx, content/docs/reference/programmatic-redirect-domain-whitelist.mdx
Adds a note to the [programmatic whitelist reference](https://main.docs.pomerium.com/docs/reference/programmatic-redirect-domain-whitelist). 
Fixes https://github.com/pomerium/pomerium/issues/4198
=> Docs: updates programmatic whitelist ref

content/docs/capabilities/programmatic-access.mdx
Adds a notice explaining the intended use of `pomerium_jwt` as an opaque token when authenticating against the API. 
Fixes #662 
Fixes #666
=> Docs: adds JWT opaque token note to doc

content/docs/capabilities/namespacing.mdx, content/docs/deploy/enterprise/configure.mdx
Removes namespaces blurb and adds idp tip to /capabilities/namespaces
=> Docs: removes namespaces blurb from configuration page

static/_redirects
Should fix the following 404ing links:
=> Docs: fixes redirects from v22 sidebar restructure

content/docs/reference/reference.json
The Branding links in reference.json were removed as part of the restructure. This PR restores those links so they all link to `/branding`.
=> Docs: restores branding refs to reference.json

content/docs/reference/reference.json
The IDP links in `reference.json` were removed as part of the restructure. This PR restores those links so they all link to `identity-provider-settings`.
=> Docs: restores idp links in reference.json

content/docs/reference/databroker.mdx, content/docs/reference/reference.json
The `databroker-storage-certificate-key-file` was removed during the Databroker Settings consolidation. This PR restores the file.
=> Docs: add databroker storage certificate key file

content/docs/quickstart.mdx
I think the link target was unintentionally removed in commit d7aab795c31a869d890aa7ccc4c4cdd104a400a7.
=> Fix broken "Certificates" link in quickstart

content/docs/reference/identity-provider-settings/readme.mdx
I think the config file key and environment variable should be 'idp_request_params' instead of 'ipd_request_params'.
=> Fix typo in Identity Provider Settings

content/docs/reference/identity-provider-settings.mdx, src/css/custom.css
Add a 'Defaults' sub-section to the Identity Provider Request Params documentation, listing the default request parameters for Apple, Azure, and Google. Add a note about the newly implemented support for clearing the default parameters entirely (from pomerium/pomerium#4315).
Also list the supported identity provider types explicitly, under Identity Provider Name.
Add a custom CSS rule to avoid some unwanted extra space when placing a code block inside a table cell.
=> Document idp_request_params default values

content/docs/reference/autocert.mdx, content/docs/reference/branding/branding.md, content/docs/reference/certificates.mdx, content/docs/reference/cookies.mdx, content/docs/reference/databroker.mdx, content/docs/reference/identity-provider-settings.mdx
This PR adds [explicit heading IDs](https://docusaurus.io/docs/next/markdown-features/toc#heading-ids) to the following reference settings pages:
- Autocert settings
- Branding settings
- Certificates settings
- Cookies settings
- Databroker settings
- IdP settings
Resolves #770
=> Docs: add stable sub headers to reference settings

content/docs/reference/identity-provider-settings.mdx
Fixes https://github.com/pomerium/pomerium/issues/4342
@kenjenkins do you think it would be helpful to add a temporary admonition below the example until you've had a chance to investigate the issue?
=> Docs: removes invalid syntax from example

content/docs/deploy/k8s/ingress.md, content/docs/deploy/k8s/reference.md, content/docs/reference/use-proxy-protocol.mdx
Resolves #797 
This PR adds the K8s annotation to `/docs/reference/use-proxy-protocol` and to `/docs/deploy/k8s/ingress`.  @wasaga Not sure about the location for this entry on the Ingress page; please let me know if it should go somewhere else.
=> Docs: add k8s proxy protocol

content/examples/go-sdk/go-app.md
Update the Go SDK example to account for API changes in the v0.0.9 Go SDK release.
=> update Go SDK example

sidebars.js
Fixes #827 
SEMrush detected markup issues on a lot of docs pages. The error claims there are issues with Breadcrumbs. This PR is a test to see if changing the URL path to an object in sidebars.js will fix the issue. If the fix works, we will apply it to all flagged pages with the issue.
=> Docs: changes /audit-log entry to object in sidebars.js

content/docs/deploy/k8s/configure.md, content/docs/deploy/k8s/ingress.md
This PR adds a bit more text to Ingress.md. The goal is to optimize the doc for keywords (`ingress controller`) without diluting it with too much text. There is also a blog post in the pipeline which covers high-level Ingress concepts, the goal being to highlight Pomerium's IC by delving into Ingress and the Ingress Controller. When it's live, we will cross-link to the blog post in the docs.
=> Docs: reformats Ingress page and adds intro sections

static/_redirects
In this [PR](https://github.com/pomerium/documentation/pull/853), the `idp_refresh_directory_settings` points to the new idp reference page. This particular setting has been deprecated and should point to the v19 upgrade guide, where an explanation for the changes and instructions to upgrade are included.
=> Docs: updates deprecated idp refresh directory settings to point to upgrade guide

content/docs/capabilities/audit-logs.mdx, content/docs/capabilities/mtls-services.mdx
Adds mTLS and Audit Logs videos to `/docs/capabilities/mtls-services` and `docs/capabilities/audit-logs`. 
Related to this [Epic](https://github.com/pomerium/internal/issues/1454)
=> Docs: adds mtls and request audit logs videos

content/docs/capabilities/mtls-clients.mdx, content/docs/capabilities/mtls-services.mdx
Update the mTLS pages in the "Capabilities" section to use the terms "downstream" and "upstream".
=> mtls: use "downstream" and "upstream" in sidebar

content/docs/capabilities/ppl.mdx
Add an entry for `client_certificate` to the table of supported PPL criteria. Add a new 'Certificate Matcher' section explaining the supported matcher conditions.
=> ppl: document new client_certificate criterion

content/docs/reference/routes/tls.mdx
Add an admonition to the TLS Downstream Client CA setting reference explaining that it is deprecated and suggesting some alternatives (see pomerium/pomerium#4356).
=> note tls_downstream_client_ca is deprecated

content/docs/capabilities/mtls-clients.mdx
Remove the instructions pertaining to the per-route CA setting. Update the configuration instructions to reference the new 'downstream_mtls' settings keys. Rephrase some of the introductory explanation, and link to the upstream mTLS guide page.
=> revise downstream mTLS capabilities page

content/docs/capabilities/ppl.mdx
Add a caution note to the Certificate Matcher section of the PPL page to explain that the syntax is subject to change.
=> ppl: note certificate matcher is beta

content/docs/reference/certificates.mdx
Add a note that the `client_ca` setting is deprecated in favor of the new `downstream_mtls.ca` setting.
Remove the `client_crl` setting entirely, as this doesn't work in current Pomerium releases.
=> mtls: note client_ca is deprecated 

content/docs/reference/certificates.mdx, static/_redirects
The `client_crl` setting does not work in current Pomerium releases (https://github.com/pomerium/pomerium/issues/4257).
=> mtls: remove client_crl

content/docs/reference/downstream-mtls-settings.mdx, content/docs/reference/reference.json
Adds the `downstream_mtls_settings` entry to `reference.json`. 
TODO:
=> Docs: adds downstream mtls settings to reference.json

content/docs/reference/cookies.mdx
Add a note to the Cookies Secure reference to explain that `cookie_secure: false` may not be used in combination with `cookie_same_site: none`.
See https://github.com/pomerium/pomerium/issues/4482.
=> add note about conflicting cookie settings

content/docs/reference/access-log-fields.mdx, content/docs/reference/authorize-log-fields.mdx
Tweak the summaries of the Access Log Fields and Authorize Log Fields reference pages to emphasize that these customize the existing logging behavior.
Move the note about `xff_num_trusted_hops` to the IP address field, not the host field.
Add a warning about the `query` log field: this should not be enabled without careful consideration.
=> update logs fields pages

content/docs/reference/routes/headers.mdx
Add a note to the Set Request Headers reference that the ID token and access token substitutions are not available when using the hosted authenticate service.
=> add note about ID/access tokens

content/docs/reference/reference.json
I did not properly realize that the reference.json file is the source of truth for the Console help links, and so I mistakenly updated the Console copy of this file directly (in https://github.com/pomerium/pomerium-console/pull/3570).
Let's make the corresponding change here, so that the Console help text does not revert when this file is next synced.
=> update Set Request Headers help text

content/docs/reference/authorize-log-fields.mdx
I believe I mixed up the behavior of the access log and the behavior of the authorize log when I added a note about `xff_num_trusted_hops` in #944.
My current understanding is that `xff_num_trusted_hops` will affect the `ip` field in the access logs, but not the `ip` field in the authorize logs.
For example, with an nginx reverse proxy in front of Pomerium and `xff_num_trusted_hops: 1`, I see log entries like this:
> all-in-one-pomerium-1  | {"level":"info","service":"authorize",**"ip":"172.25.0.4"**,"path":"/","allow":true,"allow-why-true":["user-ok"],"deny":false,"deny-why-false":[],"time":"2023-08-30T17:59:36Z","message":"authorize check"}
> all-in-one-pomerium-1  | {"level":"info","service":"envoy",**"ip":"172.25.0.1","forwarded-for":"172.25.0.1,172.25.0.4"**,"path":"/","time":"2023-08 …
=> fix authorize log 'ip' field note

content/docs/releases/upgrading.mdx
Updates v20 Core Upgrade guide headers so they match v23's. 
Related to https://github.com/pomerium/documentation/pull/981
=> Docs: fix v20 release headers

content/docs/releases/upgrading.mdx
Updates v21 Core Upgrade guide headers so they match v23's. 
Related to https://github.com/pomerium/documentation/pull/981
=> Docs: fix v21 release headers

content/docs/deploy/core/upgrading.mdx
Updates v22 Core Upgrade guide headers so they match v23's. 
Related to https://github.com/pomerium/documentation/pull/981
=> Docs: fix v22 release headers

content/docs/deploy/core/upgrading.mdx, content/docs/deploy/enterprise/upgrading.mdx
Fixes https://github.com/pomerium/internal/issues/1526
=> Docs: adds v18 and v19 notices to core and console upgrade guides

content/docs/releases/enterprise/upgrading.mdx, content/docs/releases/upgrading.mdx
Fixes broken links, which caused checks to fail in the [original backport](https://github.com/pomerium/documentation/pull/986)
=> Docs: Fixes backport to v20 broken links issue

content/docs/releases/enterprise/upgrading.mdx, content/docs/releases/upgrading.mdx
Fixes broken backport to v21. The issue is the directory changes in v22-23 broke links in v20 and v21. So the links to v18 and v19 changelogs had different paths in v20 and v21, which breaks the build.
=> Docs: backport 981 to 0 21 0

content/docs/reference/x-forwarded-for-http-header.mdx
Update the summary of the 'X-Forwarded-For HTTP Header' page to avoid the impression of a recommendation that `skip_xff_append` should be set.
The current wording of this summary is a little confusing (see https://discuss.pomerium.com/t/x-forwarded-for-docs/307).
=> clarify skip_xff_append reference

content/_install-mkcert.md, content/docs/capabilities/mtls-services.mdx, content/docs/capabilities/tcp.mdx, content/docs/deploy/core.mdx, content/docs/guides/helm.mdx, content/docs/guides/istio.mdx, content/docs/guides/securing-tcp.mdx, docusaurus.config.js
Configure 'shell-session' as an additional language for syntax highlighting in code blocks. This differs from 'bash' highlighting in that lines not beginning with a shell symbol (e.g. '$') won't be treated as part of a shell command.
Some of our existing code blocks use 'bash' along with line highlights to present interactive shell sessions. Convert these to use 'shell-session', adding '$' to any input lines.
Note that the prism-react-renderer themes do not currently have styles for the 'shell-session' token types, so we need to define our own styles for these.
Before:
After:
=> start using 'shell-session' code blocks

docusaurus.config.js, package.json, yarn.lock
This PR updates Docusaurus packages to `2.4.3` and updates `docusaurus.config.js` to use the new `plugin-google-gtag` for GA4 compatibility. 
Assuming this is all that's required to update, the only other thing that needs to be looked into is making sure we're pointing to the new GA4 tracking ID:
```js
gtag: {
trackingID: process.env.GA,
},
```
Useful Links:
- [Docusaurus plugin-google-gtag docs](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag#ex-config)
- [gtag support for multiple tracking IDs](https://docusaurus.io/blog/releases/2.4#gtag-support-for-multiple-tracking-ids)
=> Docs: updates docusaurus and adds gtag to presets

content/docs/guides/helm.mdx
Some of the Helm guide Markdown was indented too far, causing it to be rendered as a code block. Update the formatting to restore this guide content.
Fixes #996.
=> fix helm guide formatting

content/docs/capabilities/ppl.mdx
Note that the default deny rule behavior is subject to the downstream mTLS "Enforcement Mode" setting. Update the existing reference link target to the newer "Downstream mTLS Settings" page.
=> ppl: update invalid_client_certificate description

content/docs/internals/data-storage.md, content/docs/internals/troubleshooting.mdx
@kenjenkins I removed the two instances of Redis as a storage back-end for Pomerium. Is there anything else needed here?
=> Docs: removes redis as databroker sections

.github/dependabot.yaml, content/docs/deploy/k8s/reference.md, docusaurus.config.js, src/components/HomepageLayout/VideoCards.js
Just a quick cleanup PR to fix formatting on pages and code so that it prettier won't throw an error when running `yarn format`.
=> Docs: runs prettier to cleanup unrelated code and text

src/css/custom.css
Related to https://github.com/pomerium/documentation/issues/912: if we start moving the 'Examples' sub-headings inside the different tabs for Core / Console / Ingress Controller, it might make sense to demarcate the bottom of the tabs container more clearly. This change tweaks the CSS to add a rounded border around each tabs contanier.
=> add a border around the tabs container

content/docs/capabilities/getting-users-identity.md, content/docs/capabilities/original-request-context.md, content/docs/concepts/mutual-auth.md, content/docs/deploy/k8s/ingress.md, content/docs/deploy/k8s/reference.md, content/docs/guides/code-server.mdx, content/docs/guides/gitlab.mdx, content/docs/identity-providers/oidc.mdx, content/docs/reference/jwt-claim-headers.mdx, content/docs/reference/pass-identity-headers.mdx, content/docs/reference/reference.json, content/docs/reference/routes/pass-identity-headers.mdx, static/_redirects
This PR updates the global- and route-level Pass ID Headers settings so they're consistent with other settings that share global and route entries. 
Here's the main change:
- route-level Pass ID Headers is now `/reference/routes/pass-identity-headers-per-route`  
- global-level is now `/reference/pass-identity-headers` 
- the `reference.json` file has been updated to reflect these changes
@calebdoxsey and @nhayfield once this is merged, can you two update Console so that the Help Docs links don't break?
=> Docs: updates global and route pass id headers settings

.github/dependabot.yaml
For https://github.com/pomerium/internal/issues/1594
=> documentation/ci: disable dependabot for npm

content/docs/reference/reference.json
Related to https://github.com/pomerium/internal/issues/1618
This PR updates `reference.json` `short_descriptions` so that they're generic and reusable across IC, Core, Console, and Zero.
=> Docs: updates short descriptions

content/docs/reference/service-mode.mdx
Fixes a Core example that was missed in https://github.com/pomerium/documentation/pull/1114
=> Docs: fixes core service example

content/docs/reference/routes/from.mdx
This documentation was added in v0.22, so I added a backport for each  version. Please let me know if the new example makes sense, or if it's incorrect. Suggestions welcome. 
Fixes https://github.com/pomerium/internal/issues/1670
Related to https://github.com/pomerium/internal/issues/1669
=> Docs: rewrites wildcard processing order example

content/docs/deploy/core/changelog.mdx
This PR adds the v0.25 Core Changelog. Based on our release process steps, @desimone is to draft an upgrade guide. I have no problem drafting one, though.
=> Docs: adds core v0.25 changelog

content/docs/reference/cookies.mdx
=> Docs: removes cookie secure example from Enterprise tab

docusaurus.config.js, package.json, yarn.lock
Update the Docusaurus configuration to enable Mermaid diagrams, based on the current recommendation from the Docusaurus documentation.
These are working in the v0.24 docs site but are not displaying in the current v0.25 docs site.
Issue:
- https://github.com/pomerium/internal/issues/1686
=> update mermaid diagram configuration

content/docs/reference/reference.json
Update the Autocert settings entries in reference.json to link to specific section headings on the combined Autocert reference page.
Related: pomerium/pomerium-zero#1532
=> reference.json: update Autocert link paths

content/docs/reference/cookies.mdx, content/docs/reference/reference.json
Removes Cookie Secure entries from `/reference/cookies` and the `reference.json` file.
=> Docs: removes cookie secure entries from docs repo

content/docs/reference/global-timeouts.mdx, content/docs/reference/reference.json
This PR break up the global timeouts table into headers. It also adds the respective timeouts keys to the `reference.json` file. 
Related to https://github.com/pomerium/internal/issues/1699.
=> Docs: separate global timeouts

content/docs/reference/reference.json
Update the Databroker settings entries in reference.json to link to specific section headings on the combined Databroker reference page.
Related issue: https://github.com/pomerium/pomerium-zero/issues/1548
=> reference.json: update Databroker link paths

content/docs/reference/reference.json
Update the Branding settings entries in reference.json to link to specific section headings on the combined Branding reference page.
Related issue: https://github.com/pomerium/pomerium-zero/issues/1546
=> reference.json: update Branding link paths

content/docs/reference/global-timeouts.mdx
Fixes broken table formatting in `/docs/reference/global-timeouts`
=> Docs: fixes timeouts formatting

content/docs/reference/reference.json
I know we've documented internally how we document our route- and global-level conventions, but this setting predates those decisions. For now, I've updated the route-level idle timeout setting ID to `route-idle-timeout`, as that was the original name given to the route-level setting. The Console and Zero repos' help docs also label this setting "route-idle-timeout."
I've filed issues on both repos to update the ID:
- https://github.com/pomerium/pomerium-zero/issues/1564
- https://github.com/pomerium/pomerium-console/issues/3998
Fixes https://github.com/pomerium/documentation/issues/1205
=> Docs: updates route-level idle timeout ID

content/docs/deploy/enterprise/changelog.mdx
Adds the Enterprise Console `v0.25.1` patch release changelog. 
Related to https://github.com/pomerium/pomerium-console/pull/3999#event-11634180409
=> Docs: adds console changelog

content/docs/reference/routes/public-access.mdx
Fixes https://github.com/pomerium/internal/issues/1693
=> Docs: adds robots.txt notice

content/docs/reference/reference.json
This PR:
- Adds fragments to all `identity-provider-settings` paths
- Removes the `client-certificate-authority` entry
- Updates `polling-max-delay` description to use `maximum`  instead of `minimum`
**Note**: One discrepancy is the `identity-provider-polling-min-max-delay` ID in `reference.json`, which isn't consistent with the anchor link:  The anchor link is `#identity-provider-minmax-delay`, so the `path` uses this fragment instead of the key/id found in the reference file.
Resolves https://github.com/pomerium/internal/issues/1701
=> Docs: updates duplicate/missing references

content/docs/capabilities/authentication.mdx, content/docs/capabilities/authorization.mdx, content/docs/guides/jenkins.mdx, content/docs/guides/tooljet.mdx, content/docs/integrations.mdx
This PR mainly updates old admonitions, but it also adds a few:
- Tooljet guide
- Jenkins guide
- Integrations page
- Authorization
- Authentication
- Device identity
I should add this is just the initial use case for the admonition. I'd like to strategically place it with more compelling text to help broadcast Enterprise features and use cases.
Resolves https://github.com/pomerium/internal/issues/1711
=> Update Enterprise admonitions

content/docs/capabilities/authentication.mdx, content/docs/capabilities/authorization.mdx, content/docs/capabilities/branding.md, content/docs/capabilities/original-request-context.md, content/docs/guides/jenkins.mdx, content/docs/guides/tooljet.mdx, content/docs/integrations.mdx, src/theme/Admonition/Types.js
Give the EnterpriseAdmonition component the default title 'Pomerium Enterprise' to simplify usage.
=> set a default enterprise admonition title

content/docs/courses/fundamentals/self-hosted-pomerium.md
This PR updates `/docs/courses/fundamentals/self-host-pomerium` title and sidebar label to `self-hosted-authenticate`.
=> Docs: updates self-hosted pomerium title

content/docs/deploy/core/from-source.mdx
The part about "a wide array of architectures and operating systems" predates the dependency on Envoy. Currently Pomerium is limited by the OSes/architectures supported by Envoy, which I believe includes only Linux and macOS, for amd64 and arm64. (According to an announcement at https://groups.google.com/g/envoy-announce/c/2e-mSnit_BQ/m/VvweUrdaAAAJ Windows is no longer supported after Envoy 1.27.)
As of pomerium/pomerium@faa2a8652b8f001f6777d017af8f5ea021f1dc4b golangci-lint is no longer required to be installed locally (it is instead invoked via `go run`).
Finally, make sure "Pomerium" is capitalized consistently.
=> minor updates to the 'From Source' page

content/docs/reference/pass-identity-headers.mdx, content/docs/reference/routes/pass-identity-headers.mdx
This PR adds a link from the route-level pass identity headers setting to the global-level setting. It also removes the `default` column from the configuration table.
Fixes #1224
=> Updates route-level pass id headers setting

content/docs/deploy/core.mdx
I mainly wanted to add a note for https://github.com/pomerium/internal/issues/1707, but then I noticed there was a lot more on this page that could be updated. Let me know if you have any thoughts about any of these proposed changes.
---
Add a note about minimum glibc version (Linux) and minimum macOS version for the official binaries. Also replace "darwin" with the more common term "macOS".
Remove the link to the service mode setting. (We don't encouraging split service mode and I don't think it's helpful to mention this here.) Capitalize "Pomerium Core" consistently.
Add an item about the new `:vX.Y` docker image tags. Move the "minimal" link down to the section about debug images. Update the part about rootless container permissions/listening port so that it includes a link to the …
=> update 'Pomerium Core (Server)'

content/docs/internals/troubleshooting.mdx
Add a section to the Troubleshooting page to describe the permissions errors that may occur when changing the user that Pomerium runs as, with recommended resolution.
Related issue:
- https://github.com/pomerium/pomerium-zero/issues/700
=> troubleshooting: document user permissions errors

content/docs/reference/certificates.mdx, content/docs/reference/reference.json, static/_redirects
This PR removes the Client Certificate Authority setting from `/docs/reference/certificates`. It also removes the entry in `reference.json` and adds a `caution` admonition with a hard-coded link to the last supported version. 
Resolves https://github.com/pomerium/internal/issues/1704
=> Removes client ca reference page settings

content/docs/capabilities/authorization.mdx, content/docs/reference/routes/public-access.mdx
This PR updates the robots.txt behavior notice. Now, the notice is in an admonition and the text has been updated to reflect the code changes mentioned in https://github.com/pomerium/pomerium/issues/4912#issuecomment-1927795854. 
I had to close the last PR, as it included Quickstart changes from another branch (forgot to switch branches). 
Resolves https://github.com/pomerium/internal/issues/1716
=> Updates robots txt behavior notice

content/docs/reference/identity-provider-settings.mdx
Replacing current IdP min/max delay admonition with the Enterprise admonition.
=> Updates idp min max delay enterprise admonition

content/docs/deploy/enterprise.md
This PR updates the directory sync links on `/docs/deploy/enterprise`, the Enterprise landing page.
=> Updates directory sync links

content/docs/reference/reference.json
Adds a `description` in the `reference.json` file for the Databroker Storage Connection String setting. This is intended to be pulled for the Zero  Console UI.
Resolves https://github.com/pomerium/pomerium-zero/issues/1727 and https://github.com/pomerium/internal/issues/1729
=> Adds Databroker storage connection string description

content/docs/reference/reference.json
Adds a description for Global and Route Set Response Headers settings in `reference.json`
Fixes https://github.com/pomerium/pomerium-zero/issues/1740
=> Adds response header descriptions

content/docs/capabilities/enterprise-api.mdx
After reading @wasaga's Service Accounts RFC, I realized the format of a SA created in a non-global Namespace included in an admonition in `/docs/capabilities/enterprise-api` was incorrect. This PR updates the format.
=> Updates service account admonition

content/docs/integrations.mdx, content/docs/integrations/ip-ranges.mdx
This PR adds a section to our Integrations page explaining the CIDR indexing support for external data sources.
Resolves https://github.com/pomerium/internal/issues/1737
=> Adds ip range lookup support

content/docs/reference/tracing.mdx
This PR removes the HTTP protocol from the `tracing_jaeger_agent_endpoint` example in our Tracing Docs. 
Resolves https://github.com/pomerium/pomerium-zero/issues/1761
=> Removes protocol from jaeger agents endpoint example

content/docs/integrations.mdx
This PR removes the unsupported `device.id` option from the list of supported foreign keys on https://www.pomerium.com/docs/integrations#foreign-key. 
Fixes #1271
=> Removes device.id foreign key option

content/docs/internals/data-storage.md, content/docs/reference/databroker.mdx
This PR removes the **Databroker Service** entry from the databroker reference page, modifies the text, and moves the text to the internals persistence page. 
Resolves https://github.com/pomerium/internal/issues/1748.
=> Moves databroker service def to data-storage

content/docs/identity-providers/auth0.mdx, content/docs/identity-providers/azure.mdx, content/docs/identity-providers/cognito.mdx, content/docs/identity-providers/github.mdx, content/docs/identity-providers/gitlab.mdx, content/docs/identity-providers/google.mdx, content/docs/identity-providers/okta.mdx, content/docs/identity-providers/one-login.mdx, content/docs/identity-providers/ping.mdx
This PR adds query strings to Tabs. Now, when you send a link that includes an anchor link within a Tab, the page will scroll to the correct location. 
Note: I did add `queryString` to the Config and Envar Tabs, too. If you click one of these tabs, and then click another Tab in a separate  block, with a query string, it will conjoin them. For example: 
```markdown
<Tabs queryString="foo-a">
<TabItem value="bar-a"></TabItem>
<TabItem value="baz-a"></TabItem>
</Tabs>
<Tabs queryString="foo-b">
<TabItem value="bar-b"></TabItem>
<TabItem value="baz-b"></TabItem>
</Tabs>
```
Selecting `baz-a` and then `bar-b` would result in a string like:
`?foo-a=baz-a&foo-b=bar-b`. A real life example:
`/docs/identity-providers/github?configuration-settings=environment-variables&get-groups=directory-sync` …
=> adds query strings to IdP guides

content/docs/reference/reference.json
Adds a missing entry in reference.json. This is for Zero UI help docs.
=> Adds host path regex rewrite substitution entry

content/docs/capabilities/load-balancing.md, content/docs/reference/reference.json, content/docs/reference/routes/load-balancing.mdx
This PR documents Load Balancing Health Checks parameters, http health checks, tcp health checks, and grpc health checks. It adds definitions to the reference.json file. These docs were added to populate missing tooltips in Zero.
Resolves https://github.com/pomerium/internal/issues/1759
=> Updates load balancing ref page

content/docs/reference/reference.json
This PR fixes a few typos in the `reference.json` file for Load Balancing gRPC health checks settings.
=> Fixes typos in lb entries

content/docs/reference/access-log-fields.mdx, content/docs/reference/authorize-log-fields.mdx
Resolves https://github.com/pomerium/pomerium/issues/5039
=> Updates pages to remove outdated k8s notice

content/docs/reference/reference.json
Adds the response body and status entries to `reference.json` for Zero UI tooltips.
=> Adds direct response tooltips

content/docs/capabilities/authorization.mdx
This PR adds Rego documentation to the Authorize Capabilities page.
Resolves #1311
=> Adds rego docs

content/docs/community/contributing.md
Add a section to the Contributing page with a link to the main 'Building Pomerium From Source' instructions as well as instructions for running tests locally.
Related issue:
- https://github.com/pomerium/pomerium/issues/5069
=> contributing: add Development section

content/docs/capabilities/tcp.mdx
Fix an incorrect pomerium-cli version number and add a link to the GitHub release.
=> tcp: correct pomerium-cli version number

content/docs/quickstart.mdx
I noticed the note for updated the email in config.yaml was omitted from the non-enterprise quickstart, which would land a user at 403 forbidden instead of the desired page.
=> Adds prompt to change email in config.yaml like enterprise quickstart

content/docs/integrations.mdx
Add client certificate fingerprint to the list of supported keys for use with external data sources.
Related issue: https://github.com/pomerium/internal/issues/1719
=> document client cert as external data key

content/docs/capabilities/tcp.mdx, content/docs/capabilities/tcp/client.mdx, content/docs/capabilities/tcp/examples/_service-template.mdx, content/docs/capabilities/tcp/examples/git.mdx, content/docs/capabilities/tcp/examples/ms-sql.mdx, content/docs/capabilities/tcp/examples/mysql.mdx, content/docs/capabilities/tcp/examples/rdp.mdx, content/docs/capabilities/tcp/examples/redis.mdx, content/docs/capabilities/tcp/examples/ssh.mdx, content/docs/reference/routes/to.mdx
Resolves #1377 
@kenjenkins I assume this isn't available in Zero or Enterprise yet?
=> Adds tcp proxy chaining support notice

content/docs/capabilities/routing.mdx
This is a draft PR with the Routing in PZ video. You can find the video on `/docs/capabilities/routing`.
=> Adds pz routing video

content/docs/internals/data-storage.md
This PR removes a last remaining mention of the deprecated Redis storage backend on the "Persistence" page.
Closes #1390.
=> docs(data-storage): remove mention of encryption with deprecated Redis backend

docusaurus.config.js
=> adds v0.22 outdated docs notice

package.json, yarn.lock
Address some deployment build errors:
- TypeError: /opt/build/repo/static/img/logo.svg: isTSSatisfiesExpression is not a function
- Error extracting license expiry timestamp. TypeError: Cannot read properties of null
(The fix for the license error is described at https://mui.com/x/introduction/licensing/#6-invalid-license-key-typeerror-extracting-license-expiry-timestamp.)
=> build(deps): update @babel/types and @mui/x-data-grid

content/docs/reference/cookies.mdx
The here documented key cookie_expiration does not work (tested using 0.25.2), cookie_expire does work, which was documented in an older version of the docs. If the docs are meant to be correct, then maybe pomerium itself should be changed to use the updated syntax
=> FIX: use correct config key for cookie expiration

content/docs/deploy/core/changelog.mdx
Adds the v0.26 Core changelog.
=> Adds v0.26.0 Core changelog

content/docs/capabilities/high-availability.mdx, content/docs/courses/fundamentals/advanced-policies.md, content/docs/courses/fundamentals/advanced-routes.md, content/docs/courses/fundamentals/build-policies.md, content/docs/courses/fundamentals/build-routes.md, content/docs/courses/fundamentals/get-started.md, content/docs/courses/fundamentals/jwt-verification.md, content/docs/courses/fundamentals/tcp-routes.md, content/docs/guides/code-server.mdx, content/docs/guides/hedgedoc.md, content/docs/guides/jwt-verification.md, content/docs/guides/local-oidc.md, content/docs/guides/tiddlywiki.mdx, content/docs/identity-providers/oidc.mdx, content/docs/integrations/bamboohr.mdx, content/docs/integrations/zenefits.mdx, content/examples/docker/autocert.docker-compose.yml, content/examples/docker/basic.docker-compose.yml.md, content/examples/docker/nginx.docker-compose.yml, content/examples/enterprise/hosted-auth-docker.yaml.md, content/examples/jenkins/jenkins-docker-compose.md, content/examples/nginx/docker-compose.yaml.md, content/examples/tcp/docker-compose.yaml.md, content/examples/tiddlywiki/docker-compose.yaml.md, content/examples/tooljet/console-compose.yaml.md, content/examples/tooljet/docker-compose.yaml.md
This PR removes outdated `version: X` elements from all of our Docker Compose examples (related to https://github.com/lablup/backend.ai/issues/2034 and some internal discussion).
@ssveta7ak  This should be all of them, but please let me know if there are other Docker instances I missed!
=> Removes outdated version element from docker files

docusaurus.config.js
De-indexes v0.19 docs using the Docusaurus [noIndex](https://docusaurus.io/docs/next/api/docusaurus-config#noIndex) config option. After merging, we should test this in Google search to make sure its de-indexed.
Related to https://github.com/pomerium/internal/issues/1798.
=> Adds noIndex to v0.19 docs

content/docs/reference/routes/from.mdx, content/docs/reference/runtime-flags.md
Document the other two runtime flags. Update the 'How to Configure' information. Link to the port matching section on the 'From' reference page rather than repeating the port matching examples on this page.
=> update runtime flags reference page

docusaurus.config.js
Adds noIndex for v0.18 using the Docusaurus [noIndex](https://docusaurus.io/docs/next/api/docusaurus-config#noIndex) config option.
Related to https://github.com/pomerium/internal/issues/1798.
=> Adds noindex to v0.18

content/docs/internals/glossary.md
I noticed a couple broken internal links on the Glossary page.
=> glossary: fix some broken link syntax

content/docs/capabilities/custom-domains.mdx, content/docs/capabilities/ppl.mdx, content/docs/capabilities/routing.mdx
This PR adds the inline iframes from Wistia for the Routing, Policies, and Custom Domains videos. @nhayfield I had to manually add the `iframe` parameter to the URL. It seems to work, but I wanted to get your eyes on it to make sure in case I missed something.
=> Replaces loom iframes with  wistia inline iframes

content/docs/capabilities/ppl.mdx, content/docs/capabilities/routing.mdx
I think the backport for the original PR failed at https://github.com/pomerium/documentation/pull/1443#issuecomment-2155036133 because the Custom Domains page is not in the `0-26-0` branch.  However, the other Loom videos are. 
This PR replaces the Policies and Routing iframes to use Wistia.
=> Replaces loom with wistia iframes

docusaurus.config.js, src/css/custom.css, src/theme/Footer/Links/MultiColumn/index.js
Update font-awesome link to a newer version that includes a newer X/Twitter logo. Something changed about the way the CSS is structured, such that loading just the brands.min.css file is not sufficient to apply the proper font-family setting, so tweak custom.css to fix this.
Related issue:
- #1453
=> update X/Twitter logo

content/docs/troubleshooting/cluster-status.mdx
This PR updates the custom headers in `/docs/troubleshooting/cluster-status` to match exactly the returned code strings from the API. 
Resolves https://github.com/pomerium/internal/issues/1837
=> Updates anchor links to match returned code string

content/docs/capabilities/self-hosted-authenticate-service.md
Saw this one points to the new Zero quickstart instead of the Core quickstart, but it specifically names core, so it should point there.
My first PR, please give any and all directions and advice!
=> Correct core/quickstart reference

src/css/custom.css
This PR updates the `--docusaurus-highlighted-code-line-bg` background color so that the contrast is more agreeable in dark and light mode. 
In light mode, the contrast ratio is 8.64. In dark mode, it's 9.1. I got these numbers by inspecting the text in Chrome dev tools.
@kralicky and/or @kenjenkins I'd appreciate your thoughts on this. 
Resolves https://github.com/pomerium/internal/issues/1839
=> Changes highlighted code line color

static/_redirects
This PR adds redirects for pages in the `/docs/clients` directory. 
Related to https://github.com/pomerium/documentation/issues/1469
=> Updates clients redirects

content/docs/reference/runtime-flags.md
This PR documents the new Envoy resource manager runtime flag behavior. It also updates the text in other parts of the page for consistency.
@kralicky if you could review for technical accuracy, that would be appreciated. If you find the text isn't clear, or if you have suggestions for improvement, please let me know as well. Thanks!
Resolves https://github.com/pomerium/documentation/issues/1432
=> Documents envoy resource manager runtime flag

content/docs/reference/reference.json
Add 'path' property to the custom-domains entry in reference.json, now that we have a published Capabilities page for custom domains in Zero.
=> reference: add custom-domains link path

content/docs/core/changelog.mdx
Adds a link to the official [CVE statement](https://github.com/pomerium/pomerium/security/advisories/GHSA-rrqr-7w59-637v) in the `v0.26.1` Core changelog entry.
=> Adds CVE link to v0.26.1 entry in core changelog

static/_redirects
This PR fixes the following 404ing links pulled from GSC:
Related to https://github.com/pomerium/internal/issues/1841
=> Fixes a few 404 links from GSC

content/docs/zero/install.mdx, static/_redirects
This PR adds upgrading steps for Zero installations to the Zero Install at https://www.pomerium.com/docs/zero/install. 
It also adds a redirect for the removed Zero Upgrading page. 
@kralicky I requested a review from you here because I believe you pushed for the `manual` configuration steps in onboarding. Do you have suggestions for upgrade steps for manual installations? 
Resolves https://github.com/pomerium/internal/issues/1845
Related to https://github.com/pomerium/documentation/issues/1469
=> Adds upgrading steps to install page 

static/_redirects
Based on Netlify's [redirect docs](https://docs.netlify.com/routing/redirects/redirect-options/#http-status-codes), I think we have to specify a page to redirect to, so I pointed this page to our docs homepage. I also added a `410` status code. 
Resolves https://github.com/pomerium/documentation/issues/1469
=> Adds 410 redirect to Production Deployment page

src/theme/Footer/Links/MultiColumn/index.js
Replace the footer link to the public Slack with a link to https://discuss.pomerium.com instead.
=> footer: replace Slack link with Discuss forum

content/docs/troubleshooting.mdx
This PR adds an [explicit heading ID](https://docusaurus.io/docs/next/markdown-features/toc#heading-ids) to the [Upstream connection errors](https://www.pomerium.com/docs/troubleshooting#upstream-connection-errors) section on the Troubleshooting page. This should fix the linking issue described in https://github.com/pomerium/pomerium/issues/5189.
Resolves https://github.com/pomerium/pomerium/issues/5189
=> Adds envoy-error-messages header id

static/_redirects
We found a few reference setting 404s from the Google Search Console report. I don't think we have any logs from Netlify (which might be able to help us infer whether any real users are hitting these), but I thought it would make sense to add redirects for these.
Related issue:
- https://github.com/pomerium/internal/issues/1841
=> update redirects to address some 404s from GSC

cspell.json, docusaurus.config.js
Adds a Kubecon announcement bar to our docs with a link to the Google Calendar appointment page. It's not possible to selectively place this on certain pages; rather, you must apply it to all pages. 
It's also not possible to import the script @wasaga provided without swizzling the AnnouncementBar component, which seems a bit overkill when we can simply place the link in an anchor tag. 
Please let me know if this needs any other tweaks.
Resolves https://github.com/pomerium/internal/issues/1870
=> Adds kubecon banner with google calendar link

static/_redirects
Fixes the breaking `/docs/guides/vs-code-server.html` link.
=> Fixes vscode redirect

content/docs/capabilities/mtls-clients.mdx, static/_redirects
On [this page](https://www.pomerium.com/docs/capabilities/mtls-clients#install-your-client-certificate), we tell the user to import the `_wildcard` cert created from earlier in the guide. They should be importing the client cert instead. This PR updates the text to mention the correct cert.
=> Fixes typo in mTLS Clients guide

docusaurus.config.js
Related to https://github.com/pomerium/documentation/pull/1541. Pushes versions dropdown to v0.26.
=> Adds versions dropdown to latest release

content/docs/capabilities/getting-users-identity.md
Removes the `jti` claim from the JWT claims table on page https://pomerium.com/docs/capabilities/getting-users-identity
=> removes jti claim from claims table

content/docs/reference/downstream-mtls-settings.mdx
Add `user_principal_name` to the list of supported mTLS "Match Subject Alt Names" types.
Related issue:
- https://github.com/pomerium/pomerium/issues/5176
=> add new mTLS user_principal_name matcher

content/docs/internals/security.md
This PR removes the PGP key from the Security page at https://www.pomerium.com/docs/internals/security#reporting-a-security-bug. It also re-formats the page. 
I'll refrain from backporting, as https://github.com/pomerium/internal/issues/1886 is still open.
Resolves https://github.com/pomerium/internal/issues/1888
=> Removes PGP key from Security page

content/docs/k8s/ingress.md
This PR adds more clarity to the [Mutual TLS](https://www.pomerium.com/docs/k8s/ingress#mutual-tls) section in our Ingress documentation.
=> Updates k8s mutual tls text

content/docs/reference/cookies.mdx
The Markdown formatting for the cookie SameSite options table appears to have gotten mangled in https://github.com/pomerium/documentation/pull/937.
=> fix table syntax for cookie SameSite options

content/docs/capabilities/getting-users-identity.md
This PR adds a tip admonition explaining how the `jti` claim can be used to prevent session replay attempts. 
Page: https://pomerium.com/docs/capabilities/getting-users-identity
Related to https://github.com/pomerium/internal/issues/1876
=> Adds jti recommendation

docusaurus.config.js
Updates the vNext label in the Docusaurus config file so that it says "upcoming release".  I also updated the latest release label to say "latest release".
=> updates vNext versions dropdown label

content/docs/reference/downstream-mtls-settings.mdx
Update the mTLS Enforcement Mode documentation to mention that the reject_connection mode will now enable TLS connection failure logging. (This is a new feature in the upcoming v0.27 release.)
Related issue:
- https://github.com/pomerium/pomerium/issues/5130
=> document new TLS connection failure logging

content/docs/reference/routes/to.mdx
Starting in v0.27 the route `to` URL supports a new `h2c://` scheme, for HTTP/2 cleartext upstream services.
Related issue:
- https://github.com/pomerium/pomerium/issues/5213
=> document new h2c:// scheme

content/docs/reference/runtime-flags.md
This PR documents the new `pomerium_jwt_endpoint` runtime flag. 
TODO:  It might be a good idea to link from the description table to the Core v0.27 changelog and/or upgrade guide (once they are merged) so users can get further clarification on these changes.
=> Documents new pomerium_jwt_endpoint runtime flag

docusaurus.config.js
Updates the vNext versions dropdown menu. Will not be backported.
=> Updates the vNext versions dropdown

docusaurus.config.js
Updates the v0.27 dropdown menu to display `v0.27 (latest)`, not vNext.
=> Updates v0.27 dropdown

content/docs/reference/databroker.mdx, content/docs/reference/reference.json, static/_redirects
Change the page title and add a couple introductory sentences to help clarify that these settings are specifically about the databroker storage backend. Put the storage type setting first as it is the most important. Remove the settings that are currently unused. Update databroker settings redirects.
Related issues:
- https://github.com/pomerium/documentation/issues/1585
- https://github.com/pomerium/pomerium/issues/5277
=> update databroker settings reference page 

content/docs/reference/downstream-mtls-settings.mdx
The `client_ca` / `client_ca_file` config keys were [deprecated in v0.23](https://www.pomerium.com/docs/core/upgrading#new-downstream-mtls-settings) and finally [removed in v0.26](https://www.pomerium.com/docs/core/upgrading#deprecations:~:text=Support%20for%20the,about%20this%20option.). I think we can remove this note about them from the Downstream mTLS settings page. (No need to backport.)
=> remove note about older mTLS setting keys

content/docs/quickstart.mdx
The current link in our Quickstart to our "Build Routes" Zero course points to the Core guide. This PR adds the correct link.
=> Adds correct Zero Courses link

cspell.json, docusaurus.config.js, package.json, yarn.lock
This PR adds the pushfeedback widget to our docs pages. I added the `hideEmail` property to remove the email input, but we can also include the input if we want to support that option.
Tagging @gaurdro here in case he has any input as well.
=> Adds a pushfeedback widget

content/docs/reference/grpc.mdx
- Update the introductory paragraph to mention split service mode and Pomerium Enterprise.
- Tweak the "Default" column formatting for the two settings where this varies with the service mode.
- Replace "host" with "IP address" to try to avoid any potential confusion with a DNS hostname.
- Remove a confusing sentence from the "gRPC Insecure" description. (I think showing the default values in the table should be clear enough.)
Related issue:
- https://github.com/pomerium/documentation/issues/1624
=> clarify gRPC settings are for internal traffic

content/docs/core/changelog.mdx
Update the changelog for v0.27.1 to link to the GitHub security advisory for CVE-2024-47616, matching the updated release notes at https://github.com/pomerium/pomerium/releases/tag/v0.27.1.
=> changelog: add link to security advisory for v0.27.1

content/docs/reference/global-timeouts.mdx
Update the Read Timeout and Write Timeout descriptions. Call out the special behavior of the 0 value for all three. Add a sentence to discourage turning off the Read Timeout.
Related issue:
- https://github.com/pomerium/documentation/issues/1638
=> revise global timeouts explanation

content/docs/courses/fundamentals/conclusion.md, content/docs/zero.mdx, sidebars.js, static/_redirects
Manually backports changes from https://github.com/pomerium/documentation/pull/1649 to the 0-27-0 branch.
=> Manual Backport 1649 to 0 27 0

content/docs/reference/routes/path-rewriting.mdx
We've had a few issue reports suggesting that users may expect Pomerium to rewrite URLs in response bodies based on the path rewriting settings. Add a caution note to explain that Pomerium does not do this.
Related issue:
- https://github.com/pomerium/documentation/issues/1299
=> add warning to path rewriting settings

content/docs/capabilities/authorization.mdx, content/docs/capabilities/hosted-authenticate-service.md, content/docs/guides/tooljet.mdx, content/docs/identity-providers/apple.md, content/docs/identity-providers/google.mdx, content/docs/k8s/quickstart.mdx, content/examples/kubernetes/pomerium-global-settings.md, content/examples/tooljet/config-console.yaml.md, content/examples/tooljet/config-tooljet.yaml.md, content/examples/tooljet/console-compose.yaml.md, content/examples/tooljet/docker-compose.yaml.md
Docusaurus v3 appears to require double quotes around code block titles.
Related issue:
- https://github.com/pomerium/documentation/issues/1656
=> fix code block title syntax

content/docs/k8s/install.md
1. `app.kubernetes.io/instance` is the wrong label. Current `ServiceMonitor` config doesn't select the right pods.
2. For consistency, change the example namespace.
=> Fix ServiceMonitor in k8s install.md

content/docs/courses/fundamentals/conclusion.md, content/docs/guides/code-server.mdx, content/docs/zero.mdx, sidebars.js, static/_redirects
Reverts pomerium/documentation#1649
We want this in the docs as well as the marketing integrations page. There was a miscommunication.
=> Re-Adds code-server redirect to marketing integrations page

package.json, yarn.lock
Upgrading docusaurus to unblock dependabot alert.
https://github.com/pomerium/documentation/security/dependabot/47
=> upgrade docusaurus to 3.6

content/docs/zero/install.mdx
- Add instructions for installing zero with the helm chart
- Remove the old "manual" tabs, as they aren't really necessary
- Re-order tabs to put kubernetes first
=> Add zero helm chart install docs

content/docs/reference/routes/headers.mdx
Add the new `${pomerium.jwt}` token to the list of available substitutions for the set_request_headers option on the route Headers Settings page. Alphabetize the rows in this table.
Related issue:
- https://github.com/pomerium/pomerium/issues/5342
=> add pomerium.jwt token to the headers page

docusaurus.config.js
Update the version dropdown for the 0-28-0 branch to list v0.28 as the current/latest version
=> update version dropdown for v0.28

docusaurus.config.js
Replace the KubeCon announcement bar with the "This documentation is outdated" notice from the older docs site versions.
=> add "outdated" notice to v0.26 docs site

yarn.lock
This upgrades the transitive dependency path-to-regexp from 0.1.10 to 0.1.12, which should resolve a Dependabot security alert for that package.
Related issue:
- https://github.com/pomerium/documentation/security/dependabot/50
=> Bump express from 4.21.1 to 4.21.2

content/docs/concepts/device-identity.md
Links were unclickable when marked as code, so I removed that, so they hyperlink.
=> Fix formating around links and a grammar mistake

static/_redirects
In order to avoid loading an index page that immediately replaces the content with content from /docs, we are instructing the web server to 301 redirect to /docs before rendering anything in the browser.
This fixes a blank Index flash that can be seen when visiting docs.pomerium.com without a path like /docs.
=> Add server-side redirect from root to real content

content/docs/internals/connection.mdx
This was missed in prior docs PRs related to UDP and HTTP/3 work.
=> Correct our support for UDP and HTTP/3

content/docs/capabilities/getting-users-identity.mdx, content/docs/deploy/cloud/_category_.json
The unintuitive piece of this is fixing the "cloud" capitalization on the left:
The other way is to capitalize the actual folder, but we do the metadata file elsewhere, so I kept it consistent.
=> Fix sidebar capitalization and typo

content/docs/deploy/core.mdx
This improves the example Pomerium configuration file to allow someone to get up and running with Pomerium Core.
Closes #1745
=> docs: improved self-managed example configuration

content/docs/deploy/core.mdx
The PR improves the example docker snippet to demonstrate how to start Pomerium (self-managed) with a Pomerium configuration file.
closes #1746
=> docs: improved self-managed Docker documentation example

static/_redirects
- Added redirects for old capabilities pages (hosted-authenticate-service, mtls-clients, etc.).
- Updated Helm references to point to /docs/deploy/k8s/install.
- Removed outdated references (pre 0.20) and consolidated rules to avoid 404s.
- Grouped rules logically by doc category for easier maintenance.
Follow-up to [#1726](https://github.com/pomerium/documentation/pull/1726)
=> chore: update _redirects to match new sitemap (27 vs 28) and reorganized docs

static/_redirects
Follow-up to #1726 and https://github.com/pomerium/documentation/pull/1755
=> chore: update redirects to add anchors

content/docs/deploy/clients/clients.mdx, content/docs/deploy/cloud/install.mdx, content/docs/get-started/fundamentals/core/advanced-policies.md, content/docs/get-started/fundamentals/core/advanced-routes.md, content/docs/get-started/fundamentals/core/build-policies.md, content/docs/get-started/fundamentals/core/build-routes.md, content/docs/get-started/fundamentals/core/get-started.md, content/docs/get-started/fundamentals/core/jwt-verification.md, content/docs/get-started/fundamentals/core/tcp-routes.md, content/docs/get-started/fundamentals/zero/zero-advanced-routes.mdx, content/docs/get-started/fundamentals/zero/zero-build-routes.mdx, content/docs/get-started/fundamentals/zero/zero-single-sign-on.mdx, content/docs/get-started/quickstart.mdx, content/docs/guides/gitlab.mdx, content/docs/guides/guacamole.md, content/docs/guides/hedgedoc.md, content/docs/guides/tiddlywiki.mdx, content/docs/integrations/user-identity/keycloak.mdx, content/docs/internals/configuration.mdx, content/examples/docker/autocert.docker-compose.yml, content/examples/docker/basic.docker-compose.yml.md, content/examples/docker/nginx.docker-compose.yml, content/examples/enterprise/hosted-auth-docker.yaml.md, content/examples/guacamole/guacamole.docker-compose.md, content/examples/jenkins/jenkins-docker-compose.md, content/examples/nginx/docker-compose.yaml.md, content/examples/tcp/docker-compose.yaml.md, content/examples/tiddlywiki/docker-compose.yaml.md, content/examples/tooljet/console-compose.yaml.md, content/examples/tooljet/docker-compose.yaml.md
This updates pomerium.com/pomerium/* and cr.pomerium.com/* images to use their pomerium/* counterparts.
=> Use docker images without an explict domain 

docusaurus.config.js
Update the version dropdown so it contains v0.28, v0.27, and v0.26.
Related issue:
https://linear.app/pomerium/issue/ENG-1994/docs-live-site-version-dropdown-contains-two-v028-links
=> fix version dropdown

content/docs/reference/bearer-token-format.mdx
For [ENG-2085](https://linear.app/pomerium/issue/ENG-2085/document-all-possible-values-of-bearer-token-format)
=> bearer-token-format: add az example, document enterprise options

content/docs/internals/configuration.mdx
removes the split service keyword to reduce chances of landing here. 
updates language to reflect the preferred and default choice is all-in-one and split-mode has uses,but they're very specific.
=> rewrite all-in-one vs split-service

content/docs/capabilities/routes-portal.mdx, src/theme/NotFound/Content/index.tsx
This adds a bit more context to the Routes Portal feature along with FAQs for topics that have come up.
=> ENG-1873: Add narrative and FAQ to Routes Portal

_headers, cspell.json
This adds a default header that marks docs as not to be indexed.   With a follow up, we'll want to make sure we add process to make sure the current current docs are allowed to be indexed. 
From the preview deployment a curl shows we have the desired header
=> OPE-117 add _headers to not index

content/docs/deploy/upgrading.mdx, content/docs/internals/management-api-enterprise.mdx
This commit adds documentation for upgrading to Pomerium v0.29.0,
including breaking changes around tracing configuration, Enterprise API type
changes, and audit logging removal. It also fixes a broken link to the
gRPC API reference.
=> Add v0.29.0 upgrade guide

content/docs/reference/routes/headers.mdx
Start by spelling out the default behavior if no host header settings are provided. Re-order the page to put the description of the different settings first, before the table of config keys. Make sure to include `preserve_host_header` in the table.
Add a note that these settings apply just the same to the `:authority` pseudo-header (for HTTP/2 and HTTP/3 requests).
Related issue: https://linear.app/pomerium/issue/ENG-2191/docs-document-the-default-host-header-behavior-more-clearly
=> rework Host header settings reference

content/docs/internals/special-routes.md, cspell.json
This commit introduces a new documentation page dedicated to Pomerium's
internal routes under the `/.pomerium` path prefix. Previously, information
about these endpoints was fragmented or missing, making it difficult for
users and developers to understand their purpose and usage.
The new "Special Routes" page addresses this by providing a consolidated
reference. Key additions include:
- A summary table outlining each `/.pomerium/...` endpoint, its supported
HTTP methods, whether authentication is required, and its primary purpose.
- Detailed explanations for each endpoint, covering:
- `/.pomerium/`: User info HTML page.
- `/.pomerium/user`: JSON user data endpoint.
- `/.pomerium/jwt`: Deprecated JWT retrieval endpoint.
- `/.pomerium/api/v1/login`: Programmatic login URL generation.
- …
=> docs: Add documentation for special /.pomerium routes

docusaurus.config.js
By default, Prism does not support HCL, but with a config option, HCL syntax highlighting can be enabled.
This will add a splash of color to https://docs.pomerium.com/docs/deploy/enterprise/configure-terraform and any more hcl code snippets.
=> Fix Terraform HCL code formatting

content/docs/get-started/fundamentals/core/advanced-policies.md, content/docs/get-started/fundamentals/core/advanced-routes.md, content/docs/get-started/fundamentals/core/jwt-verification.md
Updated guides for Core to use file-based signing key
instead of hard-coded signing key
=> ENG-2184: Update docs to use signing_key_file

content/docs/deploy/k8s/install.md, content/docs/deploy/k8s/quickstart.mdx, content/examples/enterprise/hosted-auth-docker.yaml.md, k8s/console/deployment/image.yaml, k8s/core/kustomization.yaml
These weren't updated with the 0.28 release, so they were missed again when we moved 0.28 references to 0.29.
=> Fix version tag references that were missed

content/docs/capabilities/authentication.mdx
Although this is opt-in functionality and currently only supports Microsoft Entra ID, this capability is core to our Pomerium authentication works, so should be showcased here rather than in a separate feature capability.
=> Cover Direct IdP Authentication in our Capabilites

content/docs/deploy/core.mdx
Related issue:
https://linear.app/pomerium/issue/ENG-2232/remove-github-packages-link-from-core-docs
=> remove broken link to GitHub packages

content/docs/deploy/k8s/ingress.md
Add a missing link target in the "Pomerium-Standard Annotations" list on the Ingress Configuration page. It looks like this setting was renamed in https://github.com/pomerium/pomerium/pull/3243 (from `tls_server_name` to `tls_upstream_server_name`) but the Ingress annotation was never updated to match.
Related issue: https://linear.app/pomerium/issue/ENG-2333/ingress-controller-outdated-tls-server-name-annotation
=> add a missing ingress annotation link

content/docs/internals/connection.mdx
I happened to notice the formatting on the [Connections](https://www.pomerium.com/docs/internals/connection) page table of contents is different than other pages:
=> fix ToC formatting on Connections page

content/docs/capabilities/authentication.mdx, content/docs/reference/bearer-token-format.mdx
Update the documentation about bearer token formats. All IdPs are now supported, not just Microsoft Entra.
=> update bearer token format limitations

content/docs/reference/bearer-token-format.mdx
It should be `Authorization: Bearer TOKEN` not `Authorization: TOKEN`.
=> fix missing bearer

static/_redirects
Add redirects to resolve old 404 URLs reported in multiple issues.
- **Policy references**: Redirect `/docs/reference/policy/*` → `/docs/internals/ppl`
- **Specific policy**: Redirect `/docs/reference/policy/allowed-groups` → `/docs/internals/ppl` 
- **Guides category**: Redirect `/category/guides` → `/docs/guides`
- ✅ Follows Netlify _redirects file syntax
- ✅ Uses proper wildcard patterns with `*`
- ✅ Implements forced redirects with `301\!` status
- ✅ Works across all domains (including versioned subdomains)
Fixes #359, #333, #525
=> fix: add redirects for 404 issues

content/docs/deploy/cloud/install.mdx, content/docs/deploy/enterprise/configure-terraform.md, content/docs/deploy/k8s/gateway-api.mdx, content/docs/deploy/k8s/install.md, content/docs/deploy/k8s/quickstart.mdx, content/examples/enterprise/hosted-auth-docker.yaml.md, docusaurus.config.js, k8s/console/deployment/image.yaml, k8s/core/kustomization.yaml, src/components/docVersions.json
Also stage 0.30 branch as production ready. Next step is to branch 0-30-0 from this and then adjust the robots config and reset main to pre-release.
=> chore: update versions for Pomerium v0.30.0 release

static/_headers
0-30-0 is the only branch that should be indexed now.
=> ENG-2279: Enable bot scraping for the new release

content/docs/get-started/quickstart.mdx
This PR adds a title property to the frontmatter of the Zero Quick Start page.
Fixes #1924
**Before**
```
This file contains information about Pomerium's public documentation to help LLMs understand and reference our documentation.
Pomerium is an identity and context-aware access proxy that provides secure access to applications and services.
- [cSpell:ignore thisisunsafe, genkey, noout](content/docs/get-started/quickstart.md): Learn how to install and run Pomerium Zero in a Docker container.
```
**After**
```
This file contains information about Pomerium's public documentation to help LLMs understand and reference our documentation.
Pomerium is an identity and context-aware access proxy that provides secure access to applications and services.
- [Pomerium Zero …
```
=> fix: add title for Zero Quickstart to frontmatter

cspell.json, package.json, plugins/llms-txt-plugin.js, static/js/syft.js, yarn.lock
Backports #1921 to the 0.30 release docs.
=> fix: llms-txt uses markdown files now

content/docs/reference/routes/from.mdx
Update the list of supported URL schemes on the From URL reference page.
Related to https://linear.app/pomerium/issue/ENG-2040/document-native-ssh-access.
=> add ssh to the 'From' URL reference

content/docs/get-started/quickstart.mdx, plugins/llms-txt-plugin.js
llms.txt is correctly referencing markdown content now, but the frontmatter of the markdown files in build artifacts was retained. This can cause issues with LLMs reading the markdown files (see recommended format https://llmstxt.org/#format). As well, the what I thought was a redundant title is not, since we're stripping the frontmatter, unlike when the actual pages render, so the quickstart title is back.
An example in the deploy of frontmatter stripped, but feel free to check out other files referenced in https://deploy-preview-1931--pomerium-docs.netlify.app/llms.txt:
- https://deploy-preview-1931--pomerium-docs.netlify.app/content/docs/get-started/quickstart.md
Relates to #1924
=> fix: remove YAML frontmatter from md files for cleaner llms.txt

docusaurus.config.js
**Title:**  
Support dark/light mode auto matching system settings (#1935)
**Description:**
This PR resolves [#1935](../issues/1935) by adding support for automatically matching the app’s dark/light mode to the user’s system preference. If the user has never interacted with the theme toggle, the UI will now default to the system setting.
- Theme now defaults to system dark/light preference if toggle not set by user
- Added an **‘Auto’** mode to the theme toggle, allowing users to explicitly select system matching
- Refactored theme toggle component to handle three states: Light, Dark, and Auto
- Updated relevant documentation and tests
Please review and let me know if any further changes are needed!
**Closes:** #1935
=> feat: Support dark/light mode auto matching system settings (#1935)

content/docs/capabilities/native-ssh-access.mdx
This pull request updates the documentation for native SSH access with Pomerium, adding clarity to the SSH daemon restart process and enhancing the explanation of the authentication flow. The changes also introduce a new section explaining the Device Code OAuth flow and its importance.
* Added specific commands for restarting the SSH service on Ubuntu/Debian (`sudo systemctl restart ssh`) and RHEL/CentOS/Amazon Linux/Fedora (`sudo systemctl restart sshd`).
* Included commands to check the service status for both distributions (`sudo systemctl status ssh` and `sudo systemctl status sshd`).
* Introduced a "First Connection" section with step-by-step instructions for authenticating via OAuth, including a YouTube video embed for visual guidance.
* Added a "Subsequent Connections" section …
=> docs: Native SSH docs update

content/docs/internals/architecture.md, cspell.json
- Add databroker record structure and gRPC interface details
- Document storage backends (in-memory and Postgres)
- Add high availability section and multi-cluster deployment diagram
Credit to @calebdoxsey who wrote the actual content.
=> docs: Expand databroker technical documentation

plugins/llms-txt-plugin.js
Do not generate links for partials (files beginning with an underscore).
Related issue:
- https://github.com/pomerium/documentation/issues/1933
=> llms.txt: omit partials

content/docs/reference/service-mode.mdx
Rephrase the summary for the Service Mode reference page, to avoid implying that all-in-one mode is only for testing.
=> update service mode summary

content/examples/prometheus/prometheus.yml
when configuring Prometheus, ensure it does not reformat metric names into new UTF8 format with dots.
See https://linear.app/pomerium/issue/ENG-2726/prometheus-metrics-names-altered-after-scrape
=> alerts: force regular names
