content/docs/reference/reference.json
Adjusts the links used in Console for non-reference pages.
=> Console: fix non-reference links

content/docs/topics/getting-users-identity.md
=> Require ES256

content/examples/docker/basic.docker-compose.yml.md
Updates example docker config to connect to the verify app on `8000`.
=> update verify port in docker example

content/docs/enterprise/install/helm.mdx, content/docs/enterprise/install/quickstart.mdx, content/docs/guides/istio.mdx, content/docs/k8s/helm.mdx, content/docs/k8s/ingress.md, content/docs/production/production-deployment.md, content/docs/reference/data-broker-storage-connection-string.md, content/docs/reference/data-broker-storage-type.md, content/docs/reference/metrics-address.md, content/docs/topics/data-storage.md, content/docs/troubleshooting.mdx, content/examples/kubernetes/pomerium-certificates.yaml.md, content/examples/kubernetes/pomerium-values.yaml.md, content/examples/tcp/config.yaml.md
Replaced references to Redis with Postgres for the databroker.
=> batch of replacements for redis -> postgres

content/docs/reference/reference.json
Removes periods and brings in a copy change from @desimone to config descriptions in the console.
=> V18 shortdocs cleanup

content/docs/identity-providers/github.mdx
Resolves https://github.com/pomerium/docs/issues/78
Very minor updates:
- Noted a token permission visible in the screenshot
- gave a title to the temporary json file to match the base64 command
- Removed pagination
=> Review Update: GitHub

.github/ISSUE_TEMPLATE/doc-error.md, content/docs/guides/gitlab.mdx, content/docs/identity-providers/auth0.mdx, content/docs/identity-providers/azure.mdx, content/docs/identity-providers/gitlab.mdx, content/docs/identity-providers/okta.mdx, content/docs/identity-providers/one-login.mdx, content/docs/identity-providers/ping.mdx
- Creates an issue template for Docs issues
- Adjusts links in documentation to the new repo and template.
=> Docs Issue Template

content/docs/reference/cookie-secret-file.md, content/docs/reference/cookie-secret.md, content/docs/reference/identity-provider-client-secret-file.md, content/docs/reference/identity-provider-client-secret.md, content/docs/reference/reference.json, content/docs/reference/shared-secret-file.md, content/docs/reference/shared-secret.md, content/docs/reference/signing-key-file.md, content/docs/reference/signing-key.md
Documents new keys for several key secrets, providing them as secret files.
Resolves https://github.com/pomerium/pomerium/issues/3441
=> Document potential new config keys.

content/docs/k8s/quickstart.mdx, content/docs/k8s/reference.mdx, content/examples/kubernetes/pomerium-global-settings.md, package.json, scripts/k8sSettings.sh, scripts/k8sSettingsToJson.js, sidebars.js, src/components/K8sSettings.js, src/css/custom.css, src/ingress.pomerium.io_pomerium.yaml, src/k8sSettings.json
Document how to define Pomerium config settings in new k8s config. WIP.
=> K8s reference

content/docs/enterprise/external-data/vpn-providers.mdx
Add VPN Providers documentation.
Fixes https://github.com/pomerium/internal/issues/898
Fixes https://github.com/pomerium/pomerium-console/issues/2523
=> external-data: add vpn

content/docs/enterprise/external-data/ip-ranges.mdx
add well known ip ranges
fixes https://github.com/pomerium/datasource/issues/24
fixes https://github.com/pomerium/internal/issues/899
=> external-data: add well known ip ranges

content/docs/reference/cookie-secret-file.md, content/docs/reference/cookie-secret.md, content/docs/reference/identity-provider-client-secret-file.md, content/docs/reference/identity-provider-client-secret.md, content/docs/reference/reference.json, content/docs/reference/shared-secret-file.md, content/docs/reference/shared-secret.md, content/docs/reference/signing-key-file.md, content/docs/reference/signing-key.md
Recovers https://github.com/pomerium/documentation/pull/64
=> recover changes from PR#64

static/_redirects
Signed-off-by: Bobby DeSimone <bobbydesimone@gmail.com>
=> update _redirects to mask archive domains

content/docs/enterprise/external-data/bamboohr.mdx, content/docs/enterprise/external-data/geoip.mdx, content/docs/enterprise/external-data/ip-ranges.mdx, content/docs/enterprise/external-data/template.mdx, content/docs/enterprise/external-data/tor-exit-nodes.mdx, content/docs/enterprise/external-data/vpn-providers.mdx, content/docs/enterprise/external-data/zenefits.mdx
re-creating this PR to diagnose what happened.
=> V18 External Data Docs

docusaurus.config.js, src/components/docVersions.json
Updates v17 links to other versions.
Might need to change this PR to merge to `0-17-0`, depending on what changed while I was away.
=> update archive and sidebar links

content/docs/enterprise/install/helm.mdx, content/docs/guides/helm.mdx, content/docs/guides/istio.mdx, content/docs/guides/kubernetes.md, content/docs/k8s/ingress.md, content/docs/k8s/quickstart.mdx, content/docs/production/security.md, static/_redirects
Checking to see what, if anything, was lost upgrading the docs to v18.
=> V18 k8s quickstart

content/docs/enterprise/external-data.mdx
Added section explaining Why, link to docs
=> Update external-data.mdx with Why

content/examples/kubernetes/pomerium-global-settings.md
=> Hotfix - K8S global CRD

content/docs/topics/data-storage.md
add additional postgres configuration information
=> data-storage: add additional postgres configuration information

content/docs/reference/branding/darkmode-primary-color.md, content/docs/reference/branding/darkmode-secondary-color.md, content/docs/reference/branding/error-message-first-paragraph.md, content/docs/reference/branding/favicon-url.md, content/docs/reference/branding/logo-url.md, content/docs/reference/branding/primary-color.md, content/docs/reference/branding/secondary-color.md, content/docs/reference/policy/policy-explanation.md, content/docs/reference/policy/policy-remediation.md, content/docs/reference/reference.json, content/docs/reference/routes/regex-priority-order.md, content/docs/reference/routes/show-error-details.md
adds docs for inline help for branding, error details, and regex priority order
fixes https://github.com/pomerium/internal/issues/961
fixes https://github.com/pomerium/pomerium-console/issues/2711
=> changes for branding and error details

content/docs/guides/cors.md
Fixes https://github.com/pomerium/pomerium/issues/3609
=> add guide for cross origin setups

content/docs/reference/data-broker-storage-connection-string.md, content/docs/topics/data-storage.md
Fix https://github.com/pomerium/documentation/issues/126
=> postgres: add tip about high availability

content/docs/overview/architecture.md, content/docs/overview/background.md
Tried linking some blog posts into docs.
Files changed:
- Architecture
- Background
=> Doc blog linking patch1

package.json, yarn.lock
=> update docusaurus 2 2

.github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE, .github/ISSUE_TEMPLATE/doc-error.md
Make the default github templates for PRs more useful.
=> Update github templates

content/docs/reference/reference.json, content/docs/reference/routes/tls-upstream-allow-renegotiation.md
- https://github.com/pomerium/pomerium/issues/3481
Fixes https://github.com/pomerium/documentation/issues/176
=> add tls_upstream_allow_renegotiation option

sidebars.js
Illustrates how to add enterprise pills
fixes #175
=> another way to add the enterprise pills

src/css/custom.css
fixes https://github.com/pomerium/documentation/issues/189
=> tweak pill styles

src/components/docVersions.json
Fixes #195  ; also tests out the backport action here.
=> Fix archive versions

static/_redirects
Signed-off-by: Bobby DeSimone <bobbydesimone@gmail.com>
=> docs.pomerium.com should redirect to pomerium.com/docs Fixes #214

static/_redirects
Attempts to redirect the following links:
- https://github.com/pomerium/internal/issues/1132
- https://github.com/pomerium/internal/issues/1149
=> docs: fixes remaining 404s

yarn.lock
=> build(deps): update yarn.lock and deps

content/docs/releases/enterprise/changelog.mdx, content/docs/releases/enterprise/upgrading.mdx
chore: rename changelog.md and upgrading.md
- Closes https://github.com/pomerium/internal/issues/994
- Closes https://github.com/pomerium/internal/issues/995
- Closes https://github.com/pomerium/internal/issues/1022
- Closes https://github.com/pomerium/internal/issues/1032
- Closes https://github.com/pomerium/internal/issues/1021
- Closes https://github.com/pomerium/internal/issues/1031
=> docs: complete v0.20 chores

content/docs/releases/enterprise/install/helm.mdx, content/docs/releases/enterprise/install/kustomize.mdx, k8s/config-template/config.yaml, k8s/config-template/ingress-console.yaml, k8s/config-template/kustomization.yaml, k8s/config-template/secret.yaml, k8s/console/deployment/args.yaml, k8s/console/deployment/base.yaml, k8s/console/deployment/env.yaml, k8s/console/deployment/healthcheck.yaml, k8s/console/deployment/image.yaml, k8s/console/deployment/kustomization.yaml, k8s/console/deployment/no-root.yaml, k8s/console/deployment/ports.yaml, k8s/console/deployment/readonly-root-fs.yaml, k8s/console/deployment/scaling.yaml, k8s/console/kustomization.yaml, k8s/console/namespace.yaml, k8s/console/service/console.yaml, k8s/console/service/kustomization.yaml, k8s/core/deployment.yaml, k8s/core/kustomization.yaml, k8s/core/service.yaml, package.json, static/k8s/console.yaml, static/k8s/core.yaml, yarn.lock
- enterprise console manifests (#239)
=> backport all in one enterprise manifests to v0.20.0

content/docs/reference/cookie-expire.md, content/docs/reference/cookie-http-only.md, content/docs/reference/cookie-secure.md, content/docs/reference/reference.json
Fixes https://github.com/pomerium/documentation/issues/258
=> reference: add cookie options

content/docs/capabilities/high-availability.mdx
Fixes https://github.com/pomerium/internal/issues/1209
=> fix split mode docker compose for v21

content/docs/capabilities/high-availability.mdx
Fixes https://github.com/pomerium/internal/issues/1209
=> fix split mode using network alias

static/_redirects
=> Docs: Fixes 404ing links

content/docs/deploying/binary.mdx
Adds links to Cloudsmith and Releases repo `/docs/deploying/binary`, resolves #328 .
=> Docs: adds links to releases repo and cloudsmith

content/docs/quickstart.mdx, content/examples/config/config.docker.yaml.md, content/examples/docker/basic.docker-compose.yml.md
Removes commented certs and edits text.
=> Docs: updates Docker Compose quickstart

content/docs/internals/architecture.md
Updates component level docs. I'd like to get @calebdoxsey and @wasaga to take a look and offer any suggestions or corrections as they see fit. Databroker, for instance, could be fleshed out more. 
The diagram I'm working on will incorporate some of these steps as well.
=> Docs: updates component level docs

content/docs/concepts/access-control.mdx
Updates Access Control docs. Restructures content, adds additional sections on OAuth 2.0 and OIDC, and adds links to relevant docs and blog posts.
=> Docs: updates access control docs

content/docs/reference/branding/_category_.json
Capitalizes "Branding" sidebar label.
=> Docs: capitalizes Branding sidebar label

content/docs/concepts/zero-trust.md
Updating this with blog post links
=> Linking Docs and Blogs

content/docs/reference/dns-lookup-family.md
From https://github.com/pomerium/pomerium/pull/3957
=> add dns lookup family options

content/docs/capabilities/authentication.mdx
Updates the Authentication doc and expands on topics mentioned in the previous doc.
=> Docs: updates authn capabilities doc

content/docs/releases/enterprise/upgrading.mdx
This definitely needs a review, but from what I could see on the changelog there were only two major callouts and a ton of fixes.
=> Docs: adds release notes for v21 console

content/docs/internals/data-storage.md
Changed Persistance -> persistence
=> spellcheck

src/components/docVersions.json
Updates archived versions page to point to new v21 branch.
=> Docs: updates archived versions with v21 branch

content/docs/capabilities/getting-users-identity.md, content/docs/capabilities/jwt-verification.mdx, content/docs/guides/js-sdk.mdx, content/docs/guides/jwt-verification.md
Directed at #326.  
Updates the following docs:
- `capabilities/jwt-verification.mdx`
-  `guides/jwt-verification.md`
-  `guides/js-sdk.mdx`
-  `capabilities/getting-users-identity.md`
=> Docs: updates JWT verification in relevant files

content/docs/deploying/k8s/install.md, content/docs/deploying/k8s/quickstart.mdx, content/docs/releases/enterprise/install/kustomize.mdx
Fixes https://github.com/pomerium/documentation/issues/399
=> bump k8s to v0.21.2

content/docs/index.mdx
=> Adding Device Identity to this capabilities list

static/_redirects
=> Docs: fixes several 404s

content/docs/releases/enterprise/changelog.mdx
Adds:
- v0.20.1
- v0.21.0
- v0.21.1
=> Docs: adds console changelogs

content/docs/reference/cookie-same-site.md, content/docs/reference/reference.json
For: https://github.com/pomerium/pomerium/pull/4148
=> add cookie-same-site option

content/docs/releases/enterprise/install/kustomize.mdx, k8s/console/deployment/image.yaml, k8s/core/kustomization.yaml
=> update references for v0.22 (#618)

content/docs/releases/enterprise/configure.mdx
=> Docs: updates DNS Lookup Family default value

content/docs/releases/enterprise/install/installation.mdx
=> Docs: removes main tag from enterprise intallation

static/_redirects
=> Docs: fix redirects

content/docs/deploy/k8s/ingress.md, content/docs/reference/routes/load-balancing-policy.mdx
=> Docs: updates k8s reference and adds examples to ingress.md

content/docs/reference/routes/set-authorization-header.mdx, content/docs/reference/routes/set-request-headers.mdx
This PR updates the incorrect version numbers listed in #710. It also rewrites the `set_request_headers` Summary. 
Tagging @kenjenkins and @ssveta7ak here.
=> Docs: corrects `set_authorization_header` version number and updates text

content/docs/capabilities/getting-users-identity.md, content/docs/internals/cryptography.md
=> Docs: fix elliptic curves names

content/docs/reference/log-level.mdx
=> Docs: adds  none option to log_level reference

content/docs/reference/reference.json
@ZPain8464 Tried to fix the merge issues.
Not sure about Databroker settings
=> attempt to sync help docs

content/docs/internals/data-storage.md
=> Docs: updates backends text

content/docs/reference/identity-provider-settings.mdx
=> Docs: updates idp provider reference page

static/_redirects
Fixes #867 
Thanks, @kenjenkins. I'll be sure to add redirects to the same PRs going forward.
=> Docs: adds consolidated headers settings

content/docs/admonitions/_long-lived-connections.mdx, content/docs/capabilities/tcp.mdx, content/docs/capabilities/tcp/client.mdx, content/docs/capabilities/tcp/examples/git.mdx, content/docs/capabilities/tcp/examples/ms-sql.mdx, content/docs/capabilities/tcp/examples/mysql.mdx, content/docs/capabilities/tcp/examples/rdp.mdx, content/docs/capabilities/tcp/examples/redis.mdx, content/docs/capabilities/tcp/examples/ssh.mdx, content/docs/internals/connection.md, content/docs/internals/connection.mdx
=> Docs: terminate connections, draft 2

content/docs/capabilities/getting-users-identity.md, content/docs/index.mdx, content/docs/integrations.mdx
@cmo-pomerium and @desimone please review this when you have time. I added links in the H3s to declutter the page a bit, but we can also place links below the headers. Either way works for me.
=> Docs: updates docs homepage

content/docs/capabilities/authorization.mdx, content/docs/index.mdx
This PR adds the continuous verification video to the docs homepage and Authorization.
=> Docs: adds continuous verification

content/docs/guides/code-server.mdx
I noticed that code-server is a major entry point for some companies and search results. By doing this, we hope to improve the value prop explanation and drive more quickstart
=> Update code-server.mdx with language to introduce Pomerium

content/docs/guides/grafana.mdx
Fix the JWT header name and add `pass_identity_headers` to the Core instructions.
=> update Grafana guide

content/docs/capabilities/jwt-verification.mdx
=> Docs: updates JWT Verification iss and aud claims descriptions

content/docs/capabilities/ppl.mdx, content/docs/capabilities/routing.mdx
=> Docs: where to set policy

src/components/docVersions.json
Updates the Archived Versions json file to point to latest v23 branch.
=> Docs: updates archived versions

content/docs/admonitions/_upgrade-versions.mdx, content/docs/deploy/enterprise/upgrading.mdx
Resolves https://github.com/pomerium/internal/issues/1512
=> Docs: adds version admonition to console upgrade page

content/docs/deploy/k8s/ingress.md
Fixes https://github.com/pomerium/documentation/issues/963
=> Docs: fixes IC policy indentation and logical operator

content/docs/index.mdx
Updates a small typo on the docs homepage.
=> Docs: updates typo in homepage blurb

content/docs/capabilities/authorization.mdx
Fixes  https://github.com/pomerium/documentation/issues/1027
=> Docs: cross links ppl page

content/docs/capabilities/ppl.mdx
Resolves https://github.com/pomerium/internal/issues/1554
=> Docs: adds multiple operators example to ppl page

content/docs/reference/identity-provider-settings.mdx
Adds docs for https://github.com/pomerium/pomerium/pull/4717
=> Docs: adds idp_request_params envars example

content/docs/capabilities/enterprise-api.mdx
=> Docs: updates text and examples

content/docs/deploy/enterprise/changelog.mdx, content/docs/deploy/enterprise/upgrading.mdx
Adds v24 Console changelog and upgrade guide.
=> Docs: v24 console

content/docs/deploy/core/changelog.mdx, content/docs/deploy/core/upgrading.mdx
Adds v24 Core changelog  and upgrade guide.
=> Docs: v24 core

docusaurus.config.js
Updates the navbar to display v0.24.
=> Docs: updates navbar to show v24

content/docs/deploy/core/changelog.mdx
Fixes a small typo on the release date in the Core changelog.
=> Docs: corrects the release date

.github/dependabot.yaml, content/docs/reference/reference.json
sync helpdocs and remove dependabot automatic updates
=> sync changes with zero

content/docs/capabilities/routing.mdx, content/docs/reference/routes/from.mdx, content/docs/reference/routes/to.mdx
Resolves https://github.com/pomerium/pomerium/issues/4721
=> Docs: Clarifies route matching order

content/docs/reference/access-log-fields.mdx, content/docs/reference/authenticate-callback-path.mdx, content/docs/reference/authenticate-service-url.mdx, content/docs/reference/authorize-log-fields.mdx, content/docs/reference/cookies.mdx, content/docs/reference/global-timeouts.mdx, content/docs/reference/jwt-claim-headers.mdx, content/docs/reference/pass-identity-headers.mdx, content/docs/reference/routes/allow-any-authenticated-user.mdx, content/docs/reference/routes/headers.mdx, content/docs/reference/routes/load-balancing.mdx, content/docs/reference/routes/pass-identity-headers.mdx, content/docs/reference/routes/path-rewriting.mdx, content/docs/reference/routes/policy.mdx, content/docs/reference/routes/public-access.mdx, content/docs/reference/routes/timeouts.mdx, content/docs/reference/routes/tls.mdx, content/docs/reference/set-response-headers.mdx, content/docs/reference/use-proxy-protocol.mdx
@wasaga I've updated all the settings I could based on what we discussed. I have a list of settings we need to discuss that I'll fix in a follow-up PR. 
Related to https://github.com/pomerium/internal/issues/1630
=> Docs: updates k8s settings to use new name convention

content/docs/reference/service-mode.mdx
@kenjenkins thanks for catching this. I'm backporting the change to v22, 23, and 24.
Fixes #1113
=> Docs: fixes incorrect setting

content/docs/reference/service-mode.mdx
https://github.com/pomerium/documentation/pull/1118
=> manual backport: 1118 to 0-22-0

content/docs/reference/service-mode.mdx
https://github.com/pomerium/documentation/pull/1118
=> manual backport 1118 to 0-23-0

content/docs/deploy/enterprise/configure.mdx, content/docs/internals/troubleshooting.mdx
@kenjenkins I have a feeling this will need some changes. Any feedback is welcome. 
Fixes https://github.com/pomerium/internal/issues/1665.
=> Docs: Case sensitive string notice for Enterprise Console

content/docs/identity-providers/cognito.mdx
=> Docs: adds allow sign-out URL step to Cognito

content/docs/deploy/enterprise/upgrading.mdx
I ended up using the same text from Core.
=> Docs: adds console upgrade guide

content/docs/deploy/enterprise/changelog.mdx
@desimone I went ahead and drafted this. Ready for review.
=> Docs: adds v0.25.0 Console changelog callouts

content/docs/capabilities/ppl.mdx
Fixes https://github.com/pomerium/documentation/issues/1146.
=> Docs: groups ppl criterion

content/docs/courses/fundamentals/jwt-verification.md
Fix the link syntax for a couple of external links.
=> Fundamentals / JWT Verification page: fix links

content/docs/deploy/enterprise/install.mdx, content/examples/enterprise/hosted-auth-docker.yaml.md
Resovles https://github.com/pomerium/internal/issues/1688
=> Docs: adds v0.25 tags

static/_redirects
Related to https://github.com/pomerium/pomerium-zero/issues/1530
=> Docs: fixes pass id headers redirect

content/docs/reference/reference.json
https://app.zenhub.com/workspaces/pomerium-5f0d1eec340a620025c4dfa0/issues/gh/pomerium/pomerium-zero/1491
=> short descriptions looked weird so we removed them for these fields

content/docs/deploy/core/changelog.mdx
This PR adds the v0.25.1 patch release changelog. Does this need an upgrade guide?
=> Adds v0.25.1 core changelog

cspell.json, docusaurus-plugins/src/webpackDebugFix.js, docusaurus.config.js, package.json, yarn.lock
This PR adds the Pomerium Zero API reference to the navbar. I took the liberty of adding an APIs dropdown so users can see the Zero API and Enterprise API.
=> Adds redoc openapi plugin

content/docs/reference/reference.json
Updates the `reference.json` file definitions for route settings.
=> Updates reference definitions for Routes settings

content/docs/reference/routes/allow-any-authenticated-user.mdx
Updates reference page to include Service Accounts.
=> Updates text to mention service accounts

content/docs/reference/reference.json
Adds policy descriptions for Zero UI.
=> Adds overrides descriptions

content/docs/reference/reference.json
Adds new clusters settings and updates some existing reference.json entries.
=> Adds clusters settings to reference file

content/docs/community/contributing.md
Add a section on logging to the 'Contributing' page.
=> contributing: add note about log levels

content/docs/reference/routes/load-balancing-policy-config.mdx
Resolves https://github.com/pomerium/documentation/issues/1344
=> Updates breaking internal links

content/docs/deploy/core/changelog.mdx
Resolves https://github.com/pomerium/internal/issues/1772
=> Adds v0.25.2 Core changelog

content/docs/capabilities/custom-domains.mdx
Adds a video for Custom Domains.
=> Adds custom domains video

content/docs/capabilities/ppl.mdx
Resolves #1383 
@kenjenkins I only made the changes we discussed. Please feel free to add any other suggestions while we're here.
=> Updates ppl example

docusaurus.config.js
=> Adds v0.23 outdated docs notice

docusaurus.config.js
=> adds notice to v0.21

content/docs/quickstart.mdx, docusaurus.config.js
Resolves https://github.com/pomerium/documentation/issues/1389.
=> Adds v0.24 outdated docs notice

package.json, yarn.lock
Backport https://github.com/pomerium/documentation/commit/9f0ba4d1ba90e725a1f5d651a1ecd5f03ab63d69 from #1405
=> build(deps): update @babel/types and @mui/x-data-grid

docusaurus.config.js
=> adds v0.18 docs notice

docusaurus.config.js
=> adds v0.19 notice

docusaurus.config.js
=> Adds v0.20 outdated docs notice

content/docs/reference/reference.json
@ZPain8464 Let me know if you need any changes
=> sync help docs from zero

content/docs/deploy/enterprise/changelog.mdx
=> Adds v0.26 enterprise changelog

content/docs/deploy/core/upgrading.mdx
@kenjenkins I only made a few slight changes to the overall text. Thanks for taking the time to draft this.
=> Adds v0.26 core upgrade guide

docusaurus.config.js
=> Adds v0.25 outdated docs announcement bar

content/docs/reference/reference.json
Updates several IdP setting descriptions in the `reference.json` file so that they reflect changes in the Zero Help Docs file.
=> Updates docs descriptions to match zero help docs file

static/_redirects
Update redirects based on files moved in #1439.
Related issue:
- #1469
=> add redirects for Zero sidebar restructure

content/docs/troubleshooting/cluster-status.mdx
This PR resolves https://github.com/pomerium/pomerium-zero/issues/2345.
=> Adds persistence link to cluster status

content/docs/community.mdx
Removing slack link, funneling all users towards Discuss
=> Removing link to slack

content/docs/core/changelog.mdx
Update the Core Changelog page with the v0.26.1 release notes.
=> add v0.26.1 core changelog

yarn.lock
just the output of `yarn upgrade`
=> Update dependencies within constraints of package.json

content/docs/capabilities/ppl.mdx
Resolves https://github.com/pomerium/documentation/issues/1529
=> Adds correct video ID on PPL page

content/docs/reference/autocert.mdx
This PR updates the Autocert settings page, and resolves https://github.com/pomerium/internal/issues/1855
=> Updates autocert settings reference page

docusaurus.config.js
This is a Draft PR to experiment with versioning and updating the "Archived Versions" dropdown menu.
If we move forward with this Versions dropdown, this PR needs to merge into `main` and the versions label changed to `vNext (current)`.  
In a separate PR, we can merge into the `0-26-0` branch.
=> Update archived versions

content/docs/capabilities/custom-domains.mdx
Describe the steps needed to use your own domain name with Pomerium Zero, to help motivate the Custom Domains feature.
Related issue:
- https://github.com/pomerium/pomerium-zero/issues/2114
=> revise custom domain overview

content/docs/reference/certificates.mdx
Document which types of TLS certificates are supported.
Related issue:
- https://github.com/pomerium/pomerium-zero/issues/2803
=> Note supported certificate key types

content/docs/capabilities/hosted-authenticate-service.md
This PR updates the [Hosted Authenticate Service](https://www.pomerium.com/docs/capabilities/hosted-authenticate-service) capabilities page to include updated product information. It also spruces up the formatting and text.
Resolves https://github.com/pomerium/documentation/issues/1569
=> Updates hosted authn page

content/docs/core/changelog.mdx
This PR adds the v0.27.0 Core changelog.
=> Adds v0.27 core changelog

content/docs/enterprise/configure.mdx
Documents the new `disable_feedback_widget` Enterprise config option.
=> Documents disable_feedback_widget Enterprise setting

content/docs/enterprise/changelog.mdx
This PR includes the Enterprise Console changelog, which lists the v0.27.0 Console changelog highlights.
=> Adds v0.27.0 Enterprise changelog

content/docs/enterprise/upgrading.mdx
This PR adds the Pomerium Enterprise v0.27.0 upgrade guide.
=> Adds v0.27.0 Enterprise upgrade guide

src/components/docVersions.json
Updates the `docVersions.json` file to include v0.27.
=> Adds v0.27 to archived versions

docusaurus.config.js
Removes the "version" badge from the latest release.
=> Removes badge from latest version

content/docs/concepts/clusters.mdx, content/docs/core.mdx, content/docs/courses/fundamentals/zero-advanced-routes.mdx, content/docs/courses/fundamentals/zero-build-routes.mdx, content/docs/courses/fundamentals/zero-single-sign-on.mdx, content/docs/enterprise/install.mdx, content/docs/k8s/install.md, content/docs/k8s/quickstart.mdx, content/docs/quickstart.mdx, content/docs/zero/install.mdx, content/examples/enterprise/hosted-auth-docker.yaml.md, k8s/console/deployment/image.yaml, k8s/core/kustomization.yaml
This PR updates version tags to v0.27.0. @wasaga tagging you here for review to make sure the IC tags are updated correctly.
=> Updates version tags to v0.27.0

content/docs/enterprise/changelog.mdx
This PR documents the v0.27.1 patch release changelog for the Enterprise Console.
=> Adds v0.27.1 Console changelog

content/docs/core/changelog.mdx
This PR adds the v0.27.1 Core changelog to docs.
=> Adds v0.27.1 core changelog

content/docs/reference/grpc.mdx, content/docs/reference/reference.json, static/_redirects
Related issue:
- https://github.com/pomerium/pomerium/issues/5307
=> remove gRPC Client DNS RoundRobin setting

content/docs/reference/reference.json
For https://github.com/pomerium/pomerium-console/issues/4255
Break this setting up into separate settings.
=> add kubernetes service account token file

content/docs/capabilities/kubernetes-access.md
For https://github.com/pomerium/internal/issues/1913
=> kubernetes-access: add example group impersonation config

content/docs/k8s/install.md
For https://github.com/pomerium/pomerium-zero/issues/2344
=> k8s: use patches instead of patchesStrategicMerge

content/docs/core/changelog.mdx, content/docs/enterprise/changelog.mdx
Add core v0.27.2 and Enterprise Console v0.27.3 items to the changelog pages.
=> changelog for core v0.27.2 / enterprise v0.27.3

content/docs/core/changelog.mdx
Fix a typo in the release date for core v0.27.2.
=> changelog: fix v0.27.2 release date

content/docs/capabilities/custom-domains.mdx, content/docs/capabilities/ppl.mdx, content/docs/capabilities/routing.mdx, content/docs/courses/fundamentals/zero-build-policies.mdx, content/docs/courses/fundamentals/zero-build-routes.mdx, content/docs/courses/fundamentals/zero-single-sign-on.mdx, content/docs/guides/grafana.mdx
as title, we're shifting away from Wistia to Youtube links so I'm doing a batch update based on the ones we had uploaded
=> Update wistia links to youtube

content/docs/courses/fundamentals/conclusion.md, content/docs/zero.mdx, sidebars.js, static/_redirects
Reverts pomerium/documentation#1651
=> Revert "Manual Backport 1649 to 0-27-0"

content/docs/concepts/clusters.mdx, content/docs/core.mdx, content/docs/courses/fundamentals/zero-advanced-routes.mdx, content/docs/courses/fundamentals/zero-build-routes.mdx, content/docs/courses/fundamentals/zero-single-sign-on.mdx, content/docs/guides/code-server.mdx, content/docs/k8s/install.md, content/docs/k8s/quickstart.mdx, content/docs/quickstart.mdx, content/docs/zero/install.mdx, content/examples/enterprise/hosted-auth-docker.yaml.md, k8s/console/deployment/image.yaml, k8s/core/kustomization.yaml
Update Core and Ingress Controller version references to v0.27.2 and Enterprise Console image tag to v0.27.3.
=> update version tags to v0.27.2

content/docs/core/changelog.mdx
=> add changelog for v0.28.0

content/docs/capabilities/ppl.mdx
Add a couple sentences to document https://github.com/pomerium/pomerium/pull/5336
=> more flexible ppl matcher

src/components/docVersions.json
Updates the `docVersions.json` file to include v0.28.
=> add v0.28 to docVersions.json

yarn.lock
Resolves https://github.com/pomerium/documentation/security/dependabot/47
=> Update most dependencies - feature/fix only

content/docs/core/upgrading.mdx, content/docs/enterprise/upgrading.mdx
There are no known breaking changes in v0.28.
=> upgrading: add v0.28 note for core/enterprise

docusaurus.config.js
Add v0.28 as latest and remove v0.25.
=> update version dropdown for main branch

docusaurus.config.js
Kubecon is over, so remove the announcement bar.
=> remove announcement bar

content/docs/reference/codec-type.mdx
Document https://github.com/pomerium/internal/issues/1999.
=> settings: add http3 codec type

content/docs/admonitions/_upgrade-versions.mdx, content/docs/deploy/upgrading.mdx
For issue https://linear.app/pomerium/issue/ENG-2004/docs-add-general-pomerium-enterprise-upgrade-guide.
=> add general Enterprise upgrade instructions

content/docs/integrations/user-identity/auth0.mdx
For [ENG-2034](https://linear.app/pomerium/issue/ENG-2034/docs-update-auth0-docs), update the necessary permissions for auth0.
=> auth0: update permissions

content/docs/reference/bearer-token-format.mdx
For: https://github.com/pomerium/pomerium/pull/5545
=> bearer-token-format: remove notes about additional headers

package.json, yarn.lock
https://github.com/pomerium/documentation/compare/rsmith/dependabot-60-redoc?expand=1#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR10117
=> upgrade redocusaurus to update redoc and address dependabot alert 60

content/docs/capabilities/audit-logs.mdx, content/docs/deploy/cloud/billing.md
For [ENG-2070](https://linear.app/pomerium/issue/ENG-2070/document-how-zero-users-can-review-their-route-users)
Add docs about how users are tracked pseudonymously and how to get their information.
=> add docs for querying user information

content/docs/reference/downstream-mtls-settings.mdx
Documentation updates for https://github.com/pomerium/ingress-controller/pull/1159
=> add downstream mtls docs for ingress controller

content/docs/internals/troubleshooting.mdx, content/examples/kubernetes/pomerium-authenticate.yml, content/examples/kubernetes/pomerium-authorize.yml, content/examples/kubernetes/pomerium-databroker.yml, content/examples/kubernetes/pomerium-proxy.yml
(now fixed to use my @pomerium.com account)
=> Updated example images to use :latest instead of :main

content/docs/reference/metrics.mdx
add docs for https://github.com/pomerium/pomerium/pull/5653
=> metrics: add pgxpool

content/docs/capabilities/mcp.mdx, sidebars.js
add experimental model context protocol docs. 
https://deploy-preview-1890--pomerium-docs.netlify.app/docs/capabilities/mcp
=> mcp: add capabilities overview

content/docs/reference/circuit-breaker-thresholds.mdx
Add warning about low circuit breaker thresholds.
=> add warning about low circuit breaker thresholds

content/docs/internals/sessions.mdx
For [ENG-2513](https://linear.app/pomerium/issue/ENG-2513/document-pomerium-session-and-token-refresh-behaviors). Add documentation about sessions in Pomerium.
=> add documentation about sessions

content/docs/capabilities/authorization.mdx, content/docs/internals/architecture.md, content/docs/internals/data-storage.md, content/docs/reference/databroker.mdx
Add the new file storage type to the docs.
=> add file storage type
